# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Hidro.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1080, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1080, 720))
        font = QtGui.QFont()
        font.setUnderline(False)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget{\n"
"    background-color: #BBBBBB;\n"
"}\n"
"\n"
"QScrollBar:vertical, QScrollBar:horizontal {\n"
"    background: transparent;\n"
"    width: 10px;\n"
"    height: 10px;\n"
"    margin: 0px;\n"
"    border: none;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical, QScrollBar::handle:horizontal {\n"
"    background: #888888;\n"
"    border-radius: 5px;\n"
"    min-height: 5px;\n"
"    min-width: 5px;\n"
"}\n"
"\n"
"QScrollBar::add-line, QScrollBar::sub-line {\n"
"    background: none;\n"
"    border: none;\n"
"    height: 0px;\n"
"    width: 0px;\n"
"}\n"
"\n"
"QScrollBar::up-arrow, QScrollBar::down-arrow,\n"
"QScrollBar::left-arrow, QScrollBar::right-arrow {\n"
"    background: none;\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}\n"
"\n"
"QScrollBar::add-page, QScrollBar::sub-page {\n"
"    background: none;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.widgetSide = QtWidgets.QWidget(self.centralwidget)
        self.widgetSide.setGeometry(QtCore.QRect(0, 0, 1091, 71))
        self.widgetSide.setStyleSheet("#widgetSide{\n"
"    background-color: #000000;\n"
"}")
        self.widgetSide.setObjectName("widgetSide")
        self.decoLine2 = QtWidgets.QFrame(self.widgetSide)
        self.decoLine2.setGeometry(QtCore.QRect(40, 50, 131, 2))
        self.decoLine2.setMinimumSize(QtCore.QSize(0, 0))
        self.decoLine2.setMaximumSize(QtCore.QSize(16777215, 2))
        self.decoLine2.setStyleSheet("#decoLine2 {\n"
"    background-color: #7AE2CF;\n"
"}")
        self.decoLine2.setLineWidth(0)
        self.decoLine2.setFrameShape(QtWidgets.QFrame.HLine)
        self.decoLine2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.decoLine2.setObjectName("decoLine2")
        self.titleLabel = QtWidgets.QLabel(self.widgetSide)
        self.titleLabel.setGeometry(QtCore.QRect(0, 10, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.titleLabel.setFont(font)
        self.titleLabel.setStyleSheet("#titleLabel{\n"
"    color: #FFFFFF;\n"
"}")
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.botonVolver = QtWidgets.QPushButton(self.widgetSide)
        self.botonVolver.setGeometry(QtCore.QRect(1030, 10, 41, 51))
        self.botonVolver.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/arrow-right-circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botonVolver.setIcon(icon)
        self.botonVolver.setIconSize(QtCore.QSize(30, 30))
        self.botonVolver.setFlat(True)
        self.botonVolver.setObjectName("botonVolver")
        self.widgetMain = QtWidgets.QWidget(self.centralwidget)
        self.widgetMain.setGeometry(QtCore.QRect(0, 70, 1081, 651))
        self.widgetMain.setStyleSheet("#widgetMain {\n"
"    background-color: #111111;\n"
"}")
        self.widgetMain.setObjectName("widgetMain")
        self.widgetTablaClases = QtWidgets.QWidget(self.widgetMain)
        self.widgetTablaClases.setGeometry(QtCore.QRect(30, 50, 491, 191))
        self.widgetTablaClases.setMinimumSize(QtCore.QSize(0, 160))
        self.widgetTablaClases.setStyleSheet("#widgetTablaClases {\n"
"    border: 2px solid #888888;\n"
"    padding: 4px;\n"
"    background-color: #222222;\n"
"}")
        self.widgetTablaClases.setObjectName("widgetTablaClases")
        self.tablaResClases = QtWidgets.QTableView(self.widgetTablaClases)
        self.tablaResClases.setGeometry(QtCore.QRect(10, 10, 471, 171))
        self.tablaResClases.setMinimumSize(QtCore.QSize(0, 150))
        self.tablaResClases.setStyleSheet("#tablaResClases {\n"
"    background-color: #222222;\n"
"    color: white;\n"
"}")
        self.tablaResClases.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tablaResClases.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tablaResClases.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tablaResClases.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tablaResClases.setGridStyle(QtCore.Qt.SolidLine)
        self.tablaResClases.setObjectName("tablaResClases")
        self.tablaResClases.horizontalHeader().setDefaultSectionSize(120)
        self.tablaResClases.horizontalHeader().setMinimumSectionSize(120)
        self.tablaResClases.verticalHeader().setMinimumSectionSize(30)
        self.labelClases = QtWidgets.QLabel(self.widgetMain)
        self.labelClases.setGeometry(QtCore.QRect(30, 21, 491, 31))
        self.labelClases.setStyleSheet(".QLabel {\n"
"    color: #FFFFFF;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    padding: 4px;\n"
"    border: 2px solid #888888;\n"
"}")
        self.labelClases.setAlignment(QtCore.Qt.AlignCenter)
        self.labelClases.setObjectName("labelClases")
        self.widgetTablaFrecuencias = QtWidgets.QWidget(self.widgetMain)
        self.widgetTablaFrecuencias.setGeometry(QtCore.QRect(30, 268, 491, 131))
        self.widgetTablaFrecuencias.setStyleSheet("#widgetTablaFrecuencias {\n"
"    border: 2px solid #888888;\n"
"    padding: 4px;\n"
"    background-color: #222222;   \n"
"    border-bottom-left-radius: 5px;\n"
"    border-bottom-right-radius: 5px;\n"
"}")
        self.widgetTablaFrecuencias.setObjectName("widgetTablaFrecuencias")
        self.tablaResMuestra = QtWidgets.QTableView(self.widgetTablaFrecuencias)
        self.tablaResMuestra.setGeometry(QtCore.QRect(10, 10, 471, 111))
        self.tablaResMuestra.setStyleSheet("#tablaResMuestra {\n"
"    background-color: #222222;\n"
"    color: white;\n"
"}")
        self.tablaResMuestra.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tablaResMuestra.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tablaResMuestra.setGridStyle(QtCore.Qt.SolidLine)
        self.tablaResMuestra.setObjectName("tablaResMuestra")
        self.tablaResMuestra.horizontalHeader().setDefaultSectionSize(120)
        self.tablaResMuestra.horizontalHeader().setMinimumSectionSize(120)
        self.tablaResMuestra.verticalHeader().setMinimumSectionSize(30)
        self.labelFrecuencias = QtWidgets.QLabel(self.widgetMain)
        self.labelFrecuencias.setGeometry(QtCore.QRect(30, 239, 491, 31))
        self.labelFrecuencias.setStyleSheet(".QLabel {\n"
"    color: #FFFFFF;\n"
"    padding: 4px;\n"
"    border: 2px solid #888888;\n"
"}")
        self.labelFrecuencias.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFrecuencias.setObjectName("labelFrecuencias")
        self.botonGenerarReporte = QtWidgets.QPushButton(self.widgetMain)
        self.botonGenerarReporte.setEnabled(True)
        self.botonGenerarReporte.setGeometry(QtCore.QRect(30, 560, 491, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.botonGenerarReporte.setFont(font)
        self.botonGenerarReporte.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.botonGenerarReporte.setStyleSheet("QPushButton {\n"
"    color: #FFFFFF;\n"
"    border: 2px solid #4B8C80;\n"
"    background-color: #4B8C80;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #077A7D;\n"
"    border: 2px solid #077A7D;\n"
"}\n"
"")
        self.botonGenerarReporte.setObjectName("botonGenerarReporte")
        self.widgetOpt = QtWidgets.QWidget(self.widgetMain)
        self.widgetOpt.setGeometry(QtCore.QRect(550, 0, 531, 651))
        self.widgetOpt.setStyleSheet("#widgetOpt {\n"
"    background-color: #222222;\n"
"}")
        self.widgetOpt.setObjectName("widgetOpt")
        self.botonGenerarMarcas = QtWidgets.QPushButton(self.widgetOpt)
        self.botonGenerarMarcas.setEnabled(True)
        self.botonGenerarMarcas.setGeometry(QtCore.QRect(30, 600, 471, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.botonGenerarMarcas.setFont(font)
        self.botonGenerarMarcas.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.botonGenerarMarcas.setStyleSheet("QPushButton {\n"
"    color: #FFFFFF;\n"
"    border: 2px solid #4B8C80;\n"
"    background-color: #4B8C80;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #077A7D;\n"
"    border: 2px solid #077A7D;\n"
"}\n"
"")
        self.botonGenerarMarcas.setFlat(True)
        self.botonGenerarMarcas.setObjectName("botonGenerarMarcas")
        self.decoLine3 = QtWidgets.QFrame(self.widgetOpt)
        self.decoLine3.setGeometry(QtCore.QRect(0, 0, 2, 651))
        self.decoLine3.setMaximumSize(QtCore.QSize(10, 16777215))
        self.decoLine3.setStyleSheet("#decoLine3 {\n"
"    background-color: #7AE2CF;\n"
"}")
        self.decoLine3.setLineWidth(0)
        self.decoLine3.setFrameShape(QtWidgets.QFrame.VLine)
        self.decoLine3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.decoLine3.setObjectName("decoLine3")
        self.widgetDetalleMuestra = QtWidgets.QWidget(self.widgetOpt)
        self.widgetDetalleMuestra.setGeometry(QtCore.QRect(250, 50, 251, 111))
        self.widgetDetalleMuestra.setStyleSheet("#widgetDetalleMuestra {\n"
"    border: 2px solid #4B8C80;\n"
"    border-radius: 5px;\n"
"    padding: 4px;\n"
"    background-color: #222222;\n"
"}\n"
"\n"
".QLabel {\n"
"        color: white;\n"
"}")
        self.widgetDetalleMuestra.setObjectName("widgetDetalleMuestra")
        self.detalleMuestraNombre = QtWidgets.QLabel(self.widgetDetalleMuestra)
        self.detalleMuestraNombre.setGeometry(QtCore.QRect(20, 20, 341, 16))
        self.detalleMuestraNombre.setObjectName("detalleMuestraNombre")
        self.detalleMuestraElementos = QtWidgets.QLabel(self.widgetDetalleMuestra)
        self.detalleMuestraElementos.setGeometry(QtCore.QRect(20, 50, 341, 16))
        self.detalleMuestraElementos.setObjectName("detalleMuestraElementos")
        self.detalleMuestraFecha = QtWidgets.QLabel(self.widgetDetalleMuestra)
        self.detalleMuestraFecha.setGeometry(QtCore.QRect(20, 80, 341, 16))
        self.detalleMuestraFecha.setObjectName("detalleMuestraFecha")
        self.widgetTablaMuestras = QtWidgets.QWidget(self.widgetOpt)
        self.widgetTablaMuestras.setGeometry(QtCore.QRect(30, 50, 221, 111))
        self.widgetTablaMuestras.setStyleSheet("#widgetTablaMuestras {\n"
"    border: 2px solid #4B8C80;\n"
"    border-bottom-left-radius: 5px;\n"
"    padding: 4px;\n"
"    color: white;\n"
"    background-color: #222222;\n"
"}")
        self.widgetTablaMuestras.setObjectName("widgetTablaMuestras")
        self.listaNumGuardados = QtWidgets.QListView(self.widgetTablaMuestras)
        self.listaNumGuardados.setGeometry(QtCore.QRect(10, 10, 201, 93))
        self.listaNumGuardados.setStyleSheet("#listaNumGuardados {\n"
"    background-color: #222222;\n"
"    color: white;\n"
"}")
        self.listaNumGuardados.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listaNumGuardados.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.listaNumGuardados.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listaNumGuardados.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.listaNumGuardados.setModelColumn(0)
        self.listaNumGuardados.setObjectName("listaNumGuardados")
        self.labelClases_2 = QtWidgets.QLabel(self.widgetOpt)
        self.labelClases_2.setGeometry(QtCore.QRect(30, 20, 471, 31))
        self.labelClases_2.setStyleSheet(".QLabel {\n"
"    color: #FFFFFF;\n"
"    background-color: #4B8C80;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    padding: 4px;\n"
"}")
        self.labelClases_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelClases_2.setObjectName("labelClases_2")
        self.widgetParametros = QtWidgets.QWidget(self.widgetOpt)
        self.widgetParametros.setGeometry(QtCore.QRect(30, 240, 471, 311))
        self.widgetParametros.setStyleSheet("#widgetParametros {\n"
"    border: 2px solid #4B8C80;\n"
"    border-bottom-right-radius: 5px;\n"
"    border-bottom-left-radius: 5px;\n"
"    padding: 4px;\n"
"    background-color: #222222;\n"
"}\n"
"\n"
".QLabel {\n"
"        color: white;\n"
"}")
        self.widgetParametros.setObjectName("widgetParametros")
        self.inputLimSup = QtWidgets.QLineEdit(self.widgetParametros)
        self.inputLimSup.setEnabled(True)
        self.inputLimSup.setGeometry(QtCore.QRect(220, 40, 171, 41))
        self.inputLimSup.setStyleSheet(".QLineEdit {\n"
"    color: #FFFFFF;\n"
"    border: 2px solid #4B8C80;\n"
"    padding: 4px;\n"
"    background-color: #222222;\n"
"}")
        self.inputLimSup.setText("")
        self.inputLimSup.setAlignment(QtCore.Qt.AlignCenter)
        self.inputLimSup.setObjectName("inputLimSup")
        self.label_7 = QtWidgets.QLabel(self.widgetParametros)
        self.label_7.setGeometry(QtCore.QRect(20, 40, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet(".QLabel {\n"
"    color: #FFFFFF;\n"
"    border: 2px solid #4B8C80;\n"
"    border-top-left-radius: 5px;\n"
"    border-bottom-left-radius: 5px;\n"
"    padding: 4px;\n"
"}")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_11 = QtWidgets.QLabel(self.widgetParametros)
        self.label_11.setGeometry(QtCore.QRect(390, 40, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet(".QLabel {\n"
"    color: #FFFFFF;\n"
"    border: 2px solid #4B8C80;\n"
"    background-color: #4B8C80;\n"
"    border-top-right-radius: 5px;\n"
"    border-bottom-right-radius: 5px;\n"
"    padding: 4px;\n"
"}")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.inputLimInf = QtWidgets.QLineEdit(self.widgetParametros)
        self.inputLimInf.setEnabled(True)
        self.inputLimInf.setGeometry(QtCore.QRect(220, 90, 171, 41))
        self.inputLimInf.setStyleSheet(".QLineEdit {\n"
"    color: #FFFFFF;\n"
"    border: 2px solid #4B8C80;\n"
"    padding: 4px;\n"
"    background-color: #222222;\n"
"}")
        self.inputLimInf.setText("")
        self.inputLimInf.setAlignment(QtCore.Qt.AlignCenter)
        self.inputLimInf.setObjectName("inputLimInf")
        self.label_19 = QtWidgets.QLabel(self.widgetParametros)
        self.label_19.setGeometry(QtCore.QRect(390, 90, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet(".QLabel {\n"
"    color: #FFFFFF;\n"
"    border: 2px solid #4B8C80;\n"
"    background-color: #4B8C80;\n"
"    border-top-right-radius: 5px;\n"
"    border-bottom-right-radius: 5px;\n"
"    padding: 4px;\n"
"}")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.widgetParametros)
        self.label_20.setGeometry(QtCore.QRect(20, 90, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet(".QLabel {\n"
"    color: #FFFFFF;\n"
"    border: 2px solid #4B8C80;\n"
"    border-top-left-radius: 5px;\n"
"    border-bottom-left-radius: 5px;\n"
"    padding: 4px;\n"
"}")
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.decoLine4 = QtWidgets.QFrame(self.widgetParametros)
        self.decoLine4.setGeometry(QtCore.QRect(10, 146, 451, 1))
        self.decoLine4.setMaximumSize(QtCore.QSize(16777215, 1))
        self.decoLine4.setStyleSheet("#decoLine4 {\n"
"    background-color: #555555;\n"
"}")
        self.decoLine4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.decoLine4.setLineWidth(0)
        self.decoLine4.setFrameShape(QtWidgets.QFrame.HLine)
        self.decoLine4.setObjectName("decoLine4")
        self.label_21 = QtWidgets.QLabel(self.widgetParametros)
        self.label_21.setGeometry(QtCore.QRect(390, 180, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet(".QLabel {\n"
"    color: #FFFFFF;\n"
"    border: 2px solid #4B8C80;\n"
"    background-color: #4B8C80;\n"
"    border-top-right-radius: 5px;\n"
"    border-bottom-right-radius: 5px;\n"
"    padding: 4px;\n"
"}")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.inputMediaN = QtWidgets.QLineEdit(self.widgetParametros)
        self.inputMediaN.setEnabled(True)
        self.inputMediaN.setGeometry(QtCore.QRect(220, 180, 171, 41))
        self.inputMediaN.setStyleSheet(".QLineEdit {\n"
"    color: #FFFFFF;\n"
"    border: 2px solid #4B8C80;\n"
"    padding: 4px;\n"
"    background-color: #222222;\n"
"}")
        self.inputMediaN.setText("")
        self.inputMediaN.setAlignment(QtCore.Qt.AlignCenter)
        self.inputMediaN.setObjectName("inputMediaN")
        self.label_22 = QtWidgets.QLabel(self.widgetParametros)
        self.label_22.setGeometry(QtCore.QRect(20, 180, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet(".QLabel {\n"
"    color: #FFFFFF;\n"
"    border: 2px solid #4B8C80;\n"
"    border-top-left-radius: 5px;\n"
"    border-bottom-left-radius: 5px;\n"
"    padding: 4px;\n"
"}")
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.inputStDevN = QtWidgets.QLineEdit(self.widgetParametros)
        self.inputStDevN.setEnabled(True)
        self.inputStDevN.setGeometry(QtCore.QRect(220, 240, 171, 41))
        self.inputStDevN.setStyleSheet(".QLineEdit {\n"
"    color: #FFFFFF;\n"
"    border: 2px solid #4B8C80;\n"
"    padding: 4px;\n"
"    background-color: #222222;\n"
"}")
        self.inputStDevN.setText("")
        self.inputStDevN.setAlignment(QtCore.Qt.AlignCenter)
        self.inputStDevN.setObjectName("inputStDevN")
        self.label_23 = QtWidgets.QLabel(self.widgetParametros)
        self.label_23.setGeometry(QtCore.QRect(20, 240, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet(".QLabel {\n"
"    color: #FFFFFF;\n"
"    border: 2px solid #4B8C80;\n"
"    border-top-left-radius: 5px;\n"
"    border-bottom-left-radius: 5px;\n"
"    padding: 4px;\n"
"}")
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.widgetParametros)
        self.label_24.setGeometry(QtCore.QRect(390, 240, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet(".QLabel {\n"
"    color: #FFFFFF;\n"
"    border: 2px solid #4B8C80;\n"
"    background-color: #4B8C80;\n"
"    border-top-right-radius: 5px;\n"
"    border-bottom-right-radius: 5px;\n"
"    padding: 4px;\n"
"}")
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.label = QtWidgets.QLabel(self.widgetParametros)
        self.label.setGeometry(QtCore.QRect(20, 14, 121, 16))
        self.label.setStyleSheet("color: #CCCCCC;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widgetParametros)
        self.label_2.setGeometry(QtCore.QRect(20, 156, 221, 16))
        self.label_2.setStyleSheet("color: #CCCCCC;")
        self.label_2.setObjectName("label_2")
        self.labelClases_3 = QtWidgets.QLabel(self.widgetOpt)
        self.labelClases_3.setGeometry(QtCore.QRect(30, 210, 471, 31))
        self.labelClases_3.setStyleSheet(".QLabel {\n"
"    color: #FFFFFF;\n"
"    background-color: #4B8C80;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    padding: 4px;\n"
"}")
        self.labelClases_3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelClases_3.setObjectName("labelClases_3")
        self.widgetClassOpt = QtWidgets.QWidget(self.widgetMain)
        self.widgetClassOpt.setGeometry(QtCore.QRect(30, 420, 491, 80))
        self.widgetClassOpt.setStyleSheet("#widgetClassOpt {\n"
"    border: 2px solid #888888;\n"
"    padding: 4px;\n"
"    border-radius: 5px;\n"
"}")
        self.widgetClassOpt.setObjectName("widgetClassOpt")
        self.decoLine5 = QtWidgets.QFrame(self.widgetClassOpt)
        self.decoLine5.setGeometry(QtCore.QRect(244, 10, 1, 61))
        self.decoLine5.setMaximumSize(QtCore.QSize(1, 16777215))
        self.decoLine5.setStyleSheet("#decoLine5 {\n"
"    background-color: #555555;\n"
"}")
        self.decoLine5.setLineWidth(0)
        self.decoLine5.setFrameShape(QtWidgets.QFrame.VLine)
        self.decoLine5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.decoLine5.setObjectName("decoLine5")
        self.label_14 = QtWidgets.QLabel(self.widgetClassOpt)
        self.label_14.setGeometry(QtCore.QRect(20, 10, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet(".QLabel {\n"
"    color: white;\n"
"}")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.inputAmpClases = QtWidgets.QLineEdit(self.widgetClassOpt)
        self.inputAmpClases.setEnabled(True)
        self.inputAmpClases.setGeometry(QtCore.QRect(20, 38, 201, 31))
        self.inputAmpClases.setStyleSheet(".QLineEdit {\n"
"    border: 2px solid #6ac3b3;\n"
"    border-radius: 5px;\n"
"    padding: 4px;\n"
"    background-color: #222222;\n"
"    color: white;\n"
"}\n"
"")
        self.inputAmpClases.setAlignment(QtCore.Qt.AlignCenter)
        self.inputAmpClases.setObjectName("inputAmpClases")
        self.inputNumClases = QtWidgets.QLineEdit(self.widgetClassOpt)
        self.inputNumClases.setEnabled(True)
        self.inputNumClases.setGeometry(QtCore.QRect(270, 38, 201, 31))
        self.inputNumClases.setStyleSheet(".QLineEdit {\n"
"    border: 2px solid #6ac3b3;\n"
"    border-radius: 5px;\n"
"    padding: 4px;\n"
"    background-color: #222222;\n"
"    color: white;\n"
"}\n"
"")
        self.inputNumClases.setText("")
        self.inputNumClases.setAlignment(QtCore.Qt.AlignCenter)
        self.inputNumClases.setObjectName("inputNumClases")
        self.label_15 = QtWidgets.QLabel(self.widgetClassOpt)
        self.label_15.setGeometry(QtCore.QRect(270, 10, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet(".QLabel {\n"
"    color: white;\n"
"}")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.botonVerReportes = QtWidgets.QPushButton(self.widgetMain)
        self.botonVerReportes.setEnabled(True)
        self.botonVerReportes.setGeometry(QtCore.QRect(30, 600, 491, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.botonVerReportes.setFont(font)
        self.botonVerReportes.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.botonVerReportes.setStyleSheet("QPushButton {\n"
"    color: #FFFFFF;\n"
"    border: 2px solid #888888;\n"
"    background-color: #888888;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #666666;\n"
"    border: 2px solid #666666;\n"
"}")
        self.botonVerReportes.setObjectName("botonVerReportes")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.titleLabel.setText(_translate("MainWindow", "HidroStat"))
        self.labelClases.setText(_translate("MainWindow", "Reporte de Rangos"))
        self.labelFrecuencias.setText(_translate("MainWindow", "Reporte de la Muestra"))
        self.botonGenerarReporte.setText(_translate("MainWindow", "Crear Nuevo Reporte"))
        self.botonGenerarMarcas.setText(_translate("MainWindow", "Analizar Muestra"))
        self.detalleMuestraNombre.setText(_translate("MainWindow", "Código de Muestreo: (No seleccionada)"))
        self.detalleMuestraElementos.setText(_translate("MainWindow", "Días de Muestra: (No seleccionada)"))
        self.detalleMuestraFecha.setText(_translate("MainWindow", "Periodo: (No seleccionada)"))
        self.labelClases_2.setText(_translate("MainWindow", "Muestreos Recolectados"))
        self.inputLimSup.setPlaceholderText(_translate("MainWindow", "300"))
        self.label_7.setText(_translate("MainWindow", "Límite Máximo del Caudal"))
        self.label_11.setText(_translate("MainWindow", "M^3/s"))
        self.inputLimInf.setPlaceholderText(_translate("MainWindow", "100"))
        self.label_19.setText(_translate("MainWindow", "M^3/s"))
        self.label_20.setText(_translate("MainWindow", "Límite Mínimo del Caudal"))
        self.label_21.setText(_translate("MainWindow", "M^3/s"))
        self.inputMediaN.setPlaceholderText(_translate("MainWindow", "200"))
        self.label_22.setText(_translate("MainWindow", "Media del Caudal"))
        self.inputStDevN.setPlaceholderText(_translate("MainWindow", "30"))
        self.label_23.setText(_translate("MainWindow", "Desvío del Caudal"))
        self.label_24.setText(_translate("MainWindow", "M^3/s"))
        self.label.setText(_translate("MainWindow", "Límites de Caudal:"))
        self.label_2.setText(_translate("MainWindow", "Datos Normales del Caudal:"))
        self.labelClases_3.setText(_translate("MainWindow", "Parámetros del análisis"))
        self.label_14.setText(_translate("MainWindow", "Salto de Intervalos (A)"))
        self.inputAmpClases.setPlaceholderText(_translate("MainWindow", "Selección Automática"))
        self.inputNumClases.setPlaceholderText(_translate("MainWindow", "Selección Automática"))
        self.label_15.setText(_translate("MainWindow", "Número de Clases (K)"))
        self.botonVerReportes.setText(_translate("MainWindow", "Ver Reportes"))
import resources.resources_rc as resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
