# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Vista_Marcas1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1080, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1080, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1080, 720))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setStyleSheet("#centralwidget {\n"
"    background-color: #BBBBBB\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.widgetAside = QtWidgets.QWidget(self.centralwidget)
        self.widgetAside.setGeometry(QtCore.QRect(0, -1, 201, 721))
        self.widgetAside.setStyleSheet("background-color:#2A4759")
        self.widgetAside.setObjectName("widgetAside")
        self.botonGenerador = QtWidgets.QPushButton(self.widgetAside)
        self.botonGenerador.setEnabled(True)
        self.botonGenerador.setGeometry(QtCore.QRect(-10, 10, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.botonGenerador.setFont(font)
        self.botonGenerador.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.botonGenerador.setStyleSheet("QPushButton {\n"
"    background-color: #273F4F;  /* color normal */\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #44687F;  /* color al presionar */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #44687F;  /* color al presionar */\n"
"    color: #F79B72;\n"
"}\n"
"QPushButton:disabled{\n"
"    background-color: #F79B72;\n"
"    color: #FFFFFF;\n"
"}")
        self.botonGenerador.setObjectName("botonGenerador")
        self.botonTests = QtWidgets.QPushButton(self.widgetAside)
        self.botonTests.setEnabled(True)
        self.botonTests.setGeometry(QtCore.QRect(-10, 60, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.botonTests.setFont(font)
        self.botonTests.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.botonTests.setStyleSheet("QPushButton {\n"
"    background-color: #273F4F;  /* color normal */\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #44687F;  /* color al presionar */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #44687F;  /* color al presionar */\n"
"    color: #F79B72;\n"
"}\n"
"QPushButton:disabled{\n"
"    background-color: #F79B72;\n"
"    color: #FFFFFF;\n"
"}")
        self.botonTests.setObjectName("botonTests")
        self.botonDistrib = QtWidgets.QPushButton(self.widgetAside)
        self.botonDistrib.setEnabled(False)
        self.botonDistrib.setGeometry(QtCore.QRect(-10, 110, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.botonDistrib.setFont(font)
        self.botonDistrib.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.botonDistrib.setStyleSheet("QPushButton {\n"
"    background-color: #273F4F;  /* color normal */\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #44687F;  /* color al presionar */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #44687F;  /* color al presionar */\n"
"    color: #F79B72;\n"
"}\n"
"QPushButton:disabled{\n"
"    background-color: #F79B72;\n"
"    color: #FFFFFF;\n"
"}")
        self.botonDistrib.setObjectName("botonDistrib")
        self.botonCerrar = QtWidgets.QPushButton(self.widgetAside)
        self.botonCerrar.setGeometry(QtCore.QRect(0, 680, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.botonCerrar.setFont(font)
        self.botonCerrar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.botonCerrar.setStyleSheet("QPushButton {\n"
"    background-color: #1E313D;\n"
"    color: white;\n"
"    border-radius: 2px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #EB5B00;\n"
"}")
        self.botonCerrar.setObjectName("botonCerrar")
        self.widgetMainContent = QtWidgets.QWidget(self.centralwidget)
        self.widgetMainContent.setEnabled(True)
        self.widgetMainContent.setGeometry(QtCore.QRect(210, 0, 611, 721))
        self.widgetMainContent.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.widgetMainContent.setToolTip("")
        self.widgetMainContent.setToolTipDuration(-1)
        self.widgetMainContent.setStyleSheet("#widgetMainContent {\n"
"    background-color: #DDDDDD\n"
"}")
        self.widgetMainContent.setObjectName("widgetMainContent")
        self.labelFrecuencias = QtWidgets.QLabel(self.widgetMainContent)
        self.labelFrecuencias.setGeometry(QtCore.QRect(10, 430, 591, 31))
        self.labelFrecuencias.setStyleSheet(".QLabel {\n"
"    color: #FFFFFF;\n"
"    background-color: #2A4759;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    padding: 4px;\n"
"}")
        self.labelFrecuencias.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFrecuencias.setObjectName("labelFrecuencias")
        self.widgetTablaClases = QtWidgets.QWidget(self.widgetMainContent)
        self.widgetTablaClases.setGeometry(QtCore.QRect(10, 200, 591, 210))
        self.widgetTablaClases.setMinimumSize(QtCore.QSize(0, 160))
        self.widgetTablaClases.setStyleSheet("#widgetTablaClases {\n"
"    border: 2px solid #2A4759;\n"
"    border-bottom-left-radius: 5px;\n"
"    border-bottom-right-radius: 5px;\n"
"    padding: 4px;\n"
"    background-color: white;\n"
"}")
        self.widgetTablaClases.setObjectName("widgetTablaClases")
        self.tablaResClases = QtWidgets.QTableView(self.widgetTablaClases)
        self.tablaResClases.setGeometry(QtCore.QRect(10, 10, 571, 192))
        self.tablaResClases.setMinimumSize(QtCore.QSize(0, 150))
        self.tablaResClases.setStyleSheet("")
        self.tablaResClases.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tablaResClases.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tablaResClases.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tablaResClases.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tablaResClases.setGridStyle(QtCore.Qt.SolidLine)
        self.tablaResClases.setObjectName("tablaResClases")
        self.tablaResClases.horizontalHeader().setDefaultSectionSize(120)
        self.tablaResClases.horizontalHeader().setMinimumSectionSize(120)
        self.tablaResClases.verticalHeader().setMinimumSectionSize(30)
        self.labelClases = QtWidgets.QLabel(self.widgetMainContent)
        self.labelClases.setGeometry(QtCore.QRect(10, 170, 591, 31))
        self.labelClases.setStyleSheet(".QLabel {\n"
"    color: #FFFFFF;\n"
"    background-color: #2A4759;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    padding: 4px;\n"
"}")
        self.labelClases.setAlignment(QtCore.Qt.AlignCenter)
        self.labelClases.setObjectName("labelClases")
        self.widgetTablaFrecuencias = QtWidgets.QWidget(self.widgetMainContent)
        self.widgetTablaFrecuencias.setGeometry(QtCore.QRect(10, 460, 591, 141))
        self.widgetTablaFrecuencias.setStyleSheet("#widgetTablaFrecuencias {\n"
"    border: 2px solid #2A4759;\n"
"    border-bottom-left-radius: 5px;\n"
"    border-bottom-right-radius: 5px;\n"
"    padding: 4px;\n"
"    background-color: white;\n"
"}")
        self.widgetTablaFrecuencias.setObjectName("widgetTablaFrecuencias")
        self.tablaResMuestra = QtWidgets.QTableView(self.widgetTablaFrecuencias)
        self.tablaResMuestra.setGeometry(QtCore.QRect(10, 10, 571, 121))
        self.tablaResMuestra.setStyleSheet("")
        self.tablaResMuestra.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tablaResMuestra.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tablaResMuestra.setGridStyle(QtCore.Qt.SolidLine)
        self.tablaResMuestra.setObjectName("tablaResMuestra")
        self.tablaResMuestra.horizontalHeader().setDefaultSectionSize(120)
        self.tablaResMuestra.horizontalHeader().setMinimumSectionSize(120)
        self.tablaResMuestra.verticalHeader().setMinimumSectionSize(30)
        self.botonGenerarReporte = QtWidgets.QPushButton(self.widgetMainContent)
        self.botonGenerarReporte.setEnabled(False)
        self.botonGenerarReporte.setGeometry(QtCore.QRect(10, 680, 591, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.botonGenerarReporte.setFont(font)
        self.botonGenerarReporte.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.botonGenerarReporte.setStyleSheet("QPushButton {\n"
"    background-color: #2A4759;\n"
"    color: #FFFFFF;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #2C3F4C;\n"
"    color: #F79B72;\n"
"}\n"
"QPushButton:disabled{\n"
"    background-color: #FFFFFF;\n"
"    border: 2px solid #2A4759;\n"
"    color: #2A4759;\n"
"}")
        self.botonGenerarReporte.setObjectName("botonGenerarReporte")
        self.labelClases_2 = QtWidgets.QLabel(self.widgetMainContent)
        self.labelClases_2.setGeometry(QtCore.QRect(10, 10, 591, 31))
        self.labelClases_2.setStyleSheet(".QLabel {\n"
"    color: #FFFFFF;\n"
"    background-color: #2A4759;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    padding: 4px;\n"
"}")
        self.labelClases_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelClases_2.setObjectName("labelClases_2")
        self.widgetTablaMuestras = QtWidgets.QWidget(self.widgetMainContent)
        self.widgetTablaMuestras.setGeometry(QtCore.QRect(10, 40, 231, 111))
        self.widgetTablaMuestras.setStyleSheet("#widgetTablaMuestras {\n"
"    border: 2px solid #2A4759;\n"
"    border-bottom-left-radius: 5px;\n"
"    padding: 4px;\n"
"    background-color: white;\n"
"}")
        self.widgetTablaMuestras.setObjectName("widgetTablaMuestras")
        self.listaNumGuardados = QtWidgets.QListView(self.widgetTablaMuestras)
        self.listaNumGuardados.setGeometry(QtCore.QRect(12, 10, 211, 93))
        self.listaNumGuardados.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listaNumGuardados.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.listaNumGuardados.setModelColumn(0)
        self.listaNumGuardados.setObjectName("listaNumGuardados")
        self.widgetDetalleMuestra = QtWidgets.QWidget(self.widgetMainContent)
        self.widgetDetalleMuestra.setGeometry(QtCore.QRect(230, 40, 371, 111))
        self.widgetDetalleMuestra.setStyleSheet("#widgetDetalleMuestra {\n"
"    border: 2px solid #2A4759;\n"
"    border-bottom-right-radius: 5px;\n"
"    padding: 4px;\n"
"    background-color: white;\n"
"}")
        self.widgetDetalleMuestra.setObjectName("widgetDetalleMuestra")
        self.detalleMuestraNombre = QtWidgets.QLabel(self.widgetDetalleMuestra)
        self.detalleMuestraNombre.setGeometry(QtCore.QRect(20, 20, 341, 16))
        self.detalleMuestraNombre.setObjectName("detalleMuestraNombre")
        self.detalleMuestraElementos = QtWidgets.QLabel(self.widgetDetalleMuestra)
        self.detalleMuestraElementos.setGeometry(QtCore.QRect(20, 50, 341, 16))
        self.detalleMuestraElementos.setObjectName("detalleMuestraElementos")
        self.detalleMuestraFecha = QtWidgets.QLabel(self.widgetDetalleMuestra)
        self.detalleMuestraFecha.setGeometry(QtCore.QRect(20, 80, 341, 16))
        self.detalleMuestraFecha.setObjectName("detalleMuestraFecha")
        self.botonGenerarMarcas = QtWidgets.QPushButton(self.widgetMainContent)
        self.botonGenerarMarcas.setEnabled(True)
        self.botonGenerarMarcas.setGeometry(QtCore.QRect(10, 630, 591, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.botonGenerarMarcas.setFont(font)
        self.botonGenerarMarcas.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.botonGenerarMarcas.setStyleSheet("QPushButton {\n"
"    background-color: #F79B72;\n"
"    color: #FFFFFF;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #44687F;\n"
"    color: #F79B72;\n"
"}\n"
"QPushButton:disabled{\n"
"    background-color: #FFFFFF;\n"
"    border: 2px solid #F79B72;\n"
"    color: #F79B72;\n"
"}")
        self.botonGenerarMarcas.setObjectName("botonGenerarMarcas")
        self.labelFrecuencias.raise_()
        self.widgetTablaClases.raise_()
        self.labelClases.raise_()
        self.widgetTablaFrecuencias.raise_()
        self.botonGenerarReporte.raise_()
        self.labelClases_2.raise_()
        self.widgetDetalleMuestra.raise_()
        self.widgetTablaMuestras.raise_()
        self.botonGenerarMarcas.raise_()
        self.widgetSideParameters = QtWidgets.QWidget(self.centralwidget)
        self.widgetSideParameters.setEnabled(True)
        self.widgetSideParameters.setGeometry(QtCore.QRect(830, 0, 251, 721))
        self.widgetSideParameters.setStyleSheet("#widgetSideParameters {\n"
"    background-color: #FFFFFF;\n"
"}")
        self.widgetSideParameters.setObjectName("widgetSideParameters")
        self.labelOpcionesD = QtWidgets.QLabel(self.widgetSideParameters)
        self.labelOpcionesD.setGeometry(QtCore.QRect(20, 10, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.labelOpcionesD.setFont(font)
        self.labelOpcionesD.setStyleSheet(".QLabel {\n"
"    color: #FFFFFF;\n"
"    background-color: #F79B72;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    padding: 4px;\n"
"}")
        self.labelOpcionesD.setAlignment(QtCore.Qt.AlignCenter)
        self.labelOpcionesD.setObjectName("labelOpcionesD")
        self.widgetDistribuciones = QtWidgets.QWidget(self.widgetSideParameters)
        self.widgetDistribuciones.setGeometry(QtCore.QRect(20, 40, 211, 71))
        self.widgetDistribuciones.setStyleSheet("#widgetDistribuciones {\n"
"    border: 2px solid #F79B72;\n"
"    border-bottom-left-radius: 5px;\n"
"    border-bottom-right-radius: 5px;\n"
"    padding: 4px;\n"
"}\n"
".QRadioButton::indicator {\n"
"    width: 10px;\n"
"    height: 10px;\n"
"    border-radius: 7px;\n"
"    border: 2px solid #F79B72;\n"
"    background: #F79B72;\n"
"}\n"
"\n"
".QRadioButton::indicator:checked {\n"
"    border: 2px solid #F79B72;\n"
"    background: #2A4759;\n"
"}")
        self.widgetDistribuciones.setObjectName("widgetDistribuciones")
        self.radioNormal = QtWidgets.QRadioButton(self.widgetDistribuciones)
        self.radioNormal.setGeometry(QtCore.QRect(20, 40, 100, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioNormal.setFont(font)
        self.radioNormal.setChecked(True)
        self.radioNormal.setObjectName("radioNormal")
        self.radioBernoulli = QtWidgets.QRadioButton(self.widgetDistribuciones)
        self.radioBernoulli.setGeometry(QtCore.QRect(20, 10, 127, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioBernoulli.setFont(font)
        self.radioBernoulli.setStyleSheet("")
        self.radioBernoulli.setChecked(False)
        self.radioBernoulli.setObjectName("radioBernoulli")
        self.labelParametros = QtWidgets.QLabel(self.widgetSideParameters)
        self.labelParametros.setGeometry(QtCore.QRect(20, 120, 211, 31))
        self.labelParametros.setStyleSheet(".QLabel {\n"
"    color: #FFFFFF;\n"
"    background-color: #F79B72;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    padding: 4px;\n"
"}")
        self.labelParametros.setAlignment(QtCore.Qt.AlignCenter)
        self.labelParametros.setObjectName("labelParametros")
        self.widgetParametros = QtWidgets.QWidget(self.widgetSideParameters)
        self.widgetParametros.setGeometry(QtCore.QRect(20, 150, 211, 161))
        self.widgetParametros.setStyleSheet("#widgetParametros {\n"
"    border: 2px solid #F79B72;\n"
"    border-bottom-left-radius: 5px;\n"
"    border-bottom-right-radius: 5px;\n"
"    padding: 4px;\n"
"}")
        self.widgetParametros.setObjectName("widgetParametros")
        self.inputLimSup = QtWidgets.QLineEdit(self.widgetParametros)
        self.inputLimSup.setEnabled(True)
        self.inputLimSup.setGeometry(QtCore.QRect(10, 40, 191, 31))
        self.inputLimSup.setStyleSheet(".QLineEdit {\n"
"    border: 2px solid #2A4759;\n"
"    border-bottom-left-radius: 5px;\n"
"    border-bottom-right-radius: 5px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
".QLineEdit:disabled {\n"
"    border: 2px solid #DDDDDD;\n"
"}")
        self.inputLimSup.setText("")
        self.inputLimSup.setAlignment(QtCore.Qt.AlignCenter)
        self.inputLimSup.setObjectName("inputLimSup")
        self.label_7 = QtWidgets.QLabel(self.widgetParametros)
        self.label_7.setGeometry(QtCore.QRect(10, 20, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet(".QLabel {\n"
"    color: #FFFFFF;\n"
"    background-color: #2A4759;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    padding: 4px;\n"
"}")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.widgetParametros)
        self.label_8.setGeometry(QtCore.QRect(10, 90, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet(".QLabel {\n"
"    color: #FFFFFF;\n"
"    background-color: #2A4759;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    padding: 4px;\n"
"}")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.inputLimInf = QtWidgets.QLineEdit(self.widgetParametros)
        self.inputLimInf.setEnabled(True)
        self.inputLimInf.setGeometry(QtCore.QRect(10, 110, 191, 31))
        self.inputLimInf.setStyleSheet(".QLineEdit {\n"
"    border: 2px solid #2A4759;\n"
"    border-bottom-left-radius: 5px;\n"
"    border-bottom-right-radius: 5px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
".QLineEdit:disabled {\n"
"    border: 2px solid #DDDDDD;\n"
"}")
        self.inputLimInf.setText("")
        self.inputLimInf.setAlignment(QtCore.Qt.AlignCenter)
        self.inputLimInf.setObjectName("inputLimInf")
        self.labelParamNormal = QtWidgets.QLabel(self.widgetSideParameters)
        self.labelParamNormal.setEnabled(True)
        self.labelParamNormal.setGeometry(QtCore.QRect(20, 320, 211, 31))
        self.labelParamNormal.setStyleSheet(".QLabel {\n"
"    color: #FFFFFF;\n"
"    background-color: #F79B72;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
".QLabel:disabled {\n"
"    border: 2px solid #CCCCCC;\n"
"    background-color: #CCCCCC;\n"
"    color: #777777\n"
"}\n"
"")
        self.labelParamNormal.setAlignment(QtCore.Qt.AlignCenter)
        self.labelParamNormal.setObjectName("labelParamNormal")
        self.widgetParametrosNormal = QtWidgets.QWidget(self.widgetSideParameters)
        self.widgetParametrosNormal.setEnabled(True)
        self.widgetParametrosNormal.setGeometry(QtCore.QRect(20, 350, 211, 161))
        self.widgetParametrosNormal.setStyleSheet("#widgetParametrosNormal {\n"
"    border: 2px solid #F79B72;\n"
"    border-bottom-left-radius: 5px;\n"
"    border-bottom-right-radius: 5px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"#widgetParametrosNormal:disabled {\n"
"    border: 2px solid #CCCCCC;\n"
"}")
        self.widgetParametrosNormal.setObjectName("widgetParametrosNormal")
        self.label_9 = QtWidgets.QLabel(self.widgetParametrosNormal)
        self.label_9.setEnabled(True)
        self.label_9.setGeometry(QtCore.QRect(10, 20, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet(".QLabel {\n"
"    color: #FFFFFF;\n"
"    background-color: #2A4759;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
".QLabel:disabled {\n"
"    border: 2px solid #CCCCCC;\n"
"    background-color: #CCCCCC;\n"
"    color: #777777\n"
"}")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.inputMediaN = QtWidgets.QLineEdit(self.widgetParametrosNormal)
        self.inputMediaN.setGeometry(QtCore.QRect(10, 40, 191, 31))
        self.inputMediaN.setStyleSheet(".QLineEdit {\n"
"    border: 2px solid #2A4759;\n"
"    border-bottom-left-radius: 5px;\n"
"    border-bottom-right-radius: 5px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
".QLineEdit:disabled {\n"
"    border: 2px solid #CCCCCC;\n"
"}")
        self.inputMediaN.setAlignment(QtCore.Qt.AlignCenter)
        self.inputMediaN.setObjectName("inputMediaN")
        self.inputStDevN = QtWidgets.QLineEdit(self.widgetParametrosNormal)
        self.inputStDevN.setEnabled(True)
        self.inputStDevN.setGeometry(QtCore.QRect(10, 110, 191, 31))
        self.inputStDevN.setStyleSheet(".QLineEdit {\n"
"    border: 2px solid #2A4759;\n"
"    border-bottom-left-radius: 5px;\n"
"    border-bottom-right-radius: 5px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
".QLineEdit:disabled {\n"
"    border: 2px solid #CCCCCC;\n"
"}")
        self.inputStDevN.setAlignment(QtCore.Qt.AlignCenter)
        self.inputStDevN.setObjectName("inputStDevN")
        self.label_10 = QtWidgets.QLabel(self.widgetParametrosNormal)
        self.label_10.setGeometry(QtCore.QRect(10, 90, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet(".QLabel {\n"
"    color: #FFFFFF;\n"
"    background-color: #2A4759;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
".QLabel:disabled {\n"
"    border: 2px solid #CCCCCC;\n"
"    background-color: #CCCCCC;\n"
"    color: #777777\n"
"}")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.labelOpcClases = QtWidgets.QLabel(self.widgetSideParameters)
        self.labelOpcClases.setEnabled(True)
        self.labelOpcClases.setGeometry(QtCore.QRect(20, 520, 211, 31))
        self.labelOpcClases.setStyleSheet(".QLabel {\n"
"    color: #FFFFFF;\n"
"    background-color: #F79B72;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
".QLabel:disabled {\n"
"    border: 2px solid #CCCCCC;\n"
"    background-color: #CCCCCC;\n"
"    color: #777777\n"
"}\n"
"")
        self.labelOpcClases.setAlignment(QtCore.Qt.AlignCenter)
        self.labelOpcClases.setObjectName("labelOpcClases")
        self.widgetParametrosClase = QtWidgets.QWidget(self.widgetSideParameters)
        self.widgetParametrosClase.setEnabled(True)
        self.widgetParametrosClase.setGeometry(QtCore.QRect(20, 550, 211, 161))
        self.widgetParametrosClase.setStyleSheet("#widgetParametrosClase {\n"
"    border: 2px solid #F79B72;\n"
"    border-bottom-left-radius: 5px;\n"
"    border-bottom-right-radius: 5px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"#widgetParametrosClase:disabled {\n"
"    border: 2px solid #CCCCCC;\n"
"}")
        self.widgetParametrosClase.setObjectName("widgetParametrosClase")
        self.label_13 = QtWidgets.QLabel(self.widgetParametrosClase)
        self.label_13.setEnabled(True)
        self.label_13.setGeometry(QtCore.QRect(10, 20, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet(".QLabel {\n"
"    color: #FFFFFF;\n"
"    background-color: #2A4759;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
".QLabel:disabled {\n"
"    border: 2px solid #CCCCCC;\n"
"    background-color: #CCCCCC;\n"
"    color: #777777\n"
"}")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.inputNumClases = QtWidgets.QLineEdit(self.widgetParametrosClase)
        self.inputNumClases.setGeometry(QtCore.QRect(10, 40, 191, 31))
        self.inputNumClases.setStyleSheet(".QLineEdit {\n"
"    border: 2px solid #2A4759;\n"
"    border-bottom-left-radius: 5px;\n"
"    border-bottom-right-radius: 5px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
".QLineEdit:disabled {\n"
"    border: 2px solid #CCCCCC;\n"
"}")
        self.inputNumClases.setAlignment(QtCore.Qt.AlignCenter)
        self.inputNumClases.setObjectName("inputNumClases")
        self.inputAmpClases = QtWidgets.QLineEdit(self.widgetParametrosClase)
        self.inputAmpClases.setEnabled(True)
        self.inputAmpClases.setGeometry(QtCore.QRect(10, 110, 191, 31))
        self.inputAmpClases.setStyleSheet(".QLineEdit {\n"
"    border: 2px solid #2A4759;\n"
"    border-bottom-left-radius: 5px;\n"
"    border-bottom-right-radius: 5px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
".QLineEdit:disabled {\n"
"    border: 2px solid #CCCCCC;\n"
"}")
        self.inputAmpClases.setAlignment(QtCore.Qt.AlignCenter)
        self.inputAmpClases.setObjectName("inputAmpClases")
        self.label_14 = QtWidgets.QLabel(self.widgetParametrosClase)
        self.label_14.setGeometry(QtCore.QRect(10, 90, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet(".QLabel {\n"
"    color: #FFFFFF;\n"
"    background-color: #2A4759;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
".QLabel:disabled {\n"
"    border: 2px solid #CCCCCC;\n"
"    background-color: #CCCCCC;\n"
"    color: #777777\n"
"}")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.radioBernoulli.clicked['bool'].connect(self.labelParamNormal.setDisabled) # type: ignore
        self.radioBernoulli.clicked['bool'].connect(self.widgetParametrosNormal.setDisabled) # type: ignore
        self.radioNormal.clicked['bool'].connect(self.labelParamNormal.setEnabled) # type: ignore
        self.radioNormal.clicked['bool'].connect(self.widgetParametrosNormal.setEnabled) # type: ignore
        self.radioBernoulli.clicked['bool'].connect(self.labelOpcClases.setDisabled) # type: ignore
        self.radioBernoulli.clicked['bool'].connect(self.widgetParametrosClase.setDisabled) # type: ignore
        self.radioNormal.clicked['bool'].connect(self.labelOpcClases.setEnabled) # type: ignore
        self.radioNormal.clicked['bool'].connect(self.widgetParametrosClase.setEnabled) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.botonGenerador.setText(_translate("MainWindow", "Generador de Números"))
        self.botonTests.setText(_translate("MainWindow", "Tests"))
        self.botonDistrib.setText(_translate("MainWindow", "Distribuciones"))
        self.botonCerrar.setText(_translate("MainWindow", "Cerrar"))
        self.labelFrecuencias.setText(_translate("MainWindow", "Tabla de Frecuencias"))
        self.labelClases.setText(_translate("MainWindow", "Tabla de Clases"))
        self.botonGenerarReporte.setText(_translate("MainWindow", "Crear Reporte"))
        self.labelClases_2.setText(_translate("MainWindow", "Muestras Disponibles"))
        self.detalleMuestraNombre.setText(_translate("MainWindow", "Nombre de la muestra: (No seleccionada)"))
        self.detalleMuestraElementos.setText(_translate("MainWindow", "Cantidad de elementos: (No seleccionada)"))
        self.detalleMuestraFecha.setText(_translate("MainWindow", "Fecha: (No seleccionada)"))
        self.botonGenerarMarcas.setText(_translate("MainWindow", "Generar Marcas"))
        self.labelOpcionesD.setText(_translate("MainWindow", "Opciones de Distribución"))
        self.radioNormal.setText(_translate("MainWindow", "Dist. Normal"))
        self.radioBernoulli.setText(_translate("MainWindow", "Dist. de Bernoulli"))
        self.labelParametros.setText(_translate("MainWindow", "Parámetros del Escenario"))
        self.inputLimSup.setPlaceholderText(_translate("MainWindow", "Número más grande"))
        self.label_7.setText(_translate("MainWindow", "Lim. Superior "))
        self.label_8.setText(_translate("MainWindow", "Lim. Inferior"))
        self.inputLimInf.setPlaceholderText(_translate("MainWindow", "Número más pequeño"))
        self.labelParamNormal.setText(_translate("MainWindow", "Parámetros de la Distribución Normal"))
        self.label_9.setText(_translate("MainWindow", "Media (μ)"))
        self.inputMediaN.setPlaceholderText(_translate("MainWindow", "Media de la distribución"))
        self.inputStDevN.setPlaceholderText(_translate("MainWindow", "Media de la distribución"))
        self.label_10.setText(_translate("MainWindow", "Desvío Est. (σ)"))
        self.labelOpcClases.setText(_translate("MainWindow", "Parámetros Opcionales de Clase"))
        self.label_13.setText(_translate("MainWindow", "Número de Clases (K)"))
        self.inputNumClases.setPlaceholderText(_translate("MainWindow", "Selección Automática"))
        self.inputAmpClases.setPlaceholderText(_translate("MainWindow", "Selección Automática"))
        self.label_14.setText(_translate("MainWindow", "Salto de Intervalos (A)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
