# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Vista_Marcas.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1080, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1080, 720))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: #CCCCCC")
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, -1, 201, 721))
        self.widget.setStyleSheet("background-color:#2A4759")
        self.widget.setObjectName("widget")
        self.botonGenerador = QtWidgets.QPushButton(self.widget)
        self.botonGenerador.setEnabled(True)
        self.botonGenerador.setGeometry(QtCore.QRect(-10, 10, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.botonGenerador.setFont(font)
        self.botonGenerador.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.botonGenerador.setStyleSheet("QPushButton {\n"
"    background-color: #273F4F;  /* color normal */\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #44687F;  /* color al presionar */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #44687F;  /* color al presionar */\n"
"    color: #F79B72;\n"
"}\n"
"QPushButton:disabled{\n"
"    background-color: #F79B72;\n"
"    color: #FFFFFF;\n"
"}")
        self.botonGenerador.setObjectName("botonGenerador")
        self.botonTests = QtWidgets.QPushButton(self.widget)
        self.botonTests.setEnabled(True)
        self.botonTests.setGeometry(QtCore.QRect(-10, 60, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.botonTests.setFont(font)
        self.botonTests.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.botonTests.setStyleSheet("QPushButton {\n"
"    background-color: #273F4F;  /* color normal */\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #44687F;  /* color al presionar */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #44687F;  /* color al presionar */\n"
"    color: #F79B72;\n"
"}\n"
"QPushButton:disabled{\n"
"    background-color: #F79B72;\n"
"    color: #FFFFFF;\n"
"}")
        self.botonTests.setObjectName("botonTests")
        self.botonDistrib = QtWidgets.QPushButton(self.widget)
        self.botonDistrib.setEnabled(False)
        self.botonDistrib.setGeometry(QtCore.QRect(-10, 110, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.botonDistrib.setFont(font)
        self.botonDistrib.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.botonDistrib.setStyleSheet("QPushButton {\n"
"    background-color: #273F4F;  /* color normal */\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #44687F;  /* color al presionar */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #44687F;  /* color al presionar */\n"
"    color: #F79B72;\n"
"}\n"
"QPushButton:disabled{\n"
"    background-color: #F79B72;\n"
"    color: #FFFFFF;\n"
"}")
        self.botonDistrib.setObjectName("botonDistrib")
        self.botonCerrar = QtWidgets.QPushButton(self.widget)
        self.botonCerrar.setGeometry(QtCore.QRect(0, 680, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.botonCerrar.setFont(font)
        self.botonCerrar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.botonCerrar.setStyleSheet("QPushButton {\n"
"    background-color: #1E313D;\n"
"    color: white;\n"
"    border-radius: 2px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #EB5B00;\n"
"}")
        self.botonCerrar.setObjectName("botonCerrar")
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(209, 0, 871, 721))
        self.widget_3.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.widget_3.setToolTip("")
        self.widget_3.setToolTipDuration(-1)
        self.widget_3.setStyleSheet("background-color: #FFFFFF")
        self.widget_3.setObjectName("widget_3")
        self.widget_4 = QtWidgets.QWidget(self.widget_3)
        self.widget_4.setGeometry(QtCore.QRect(0, 0, 871, 61))
        self.widget_4.setStyleSheet("background-color:#2A4759")
        self.widget_4.setObjectName("widget_4")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.widget_4)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 871, 61))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: #FFFFFF;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.widgetModelo = QtWidgets.QWidget(self.widget_3)
        self.widgetModelo.setGeometry(QtCore.QRect(10, 80, 241, 71))
        self.widgetModelo.setStyleSheet("#widgetModelo {\n"
"    border: 2px solid #F79B72;  /* Borde celeste suave */\n"
"    border-radius: 5px;         /* Esquinas redondeadas */\n"
"    padding: 4px;               /* Espaciado interno */\n"
"}")
        self.widgetModelo.setObjectName("widgetModelo")
        self.radioRachas = QtWidgets.QRadioButton(self.widgetModelo)
        self.radioRachas.setGeometry(QtCore.QRect(20, 30, 91, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioRachas.setFont(font)
        self.radioRachas.setChecked(True)
        self.radioRachas.setObjectName("radioRachas")
        self.radioChiCuadrado = QtWidgets.QRadioButton(self.widgetModelo)
        self.radioChiCuadrado.setGeometry(QtCore.QRect(128, 30, 101, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioChiCuadrado.setFont(font)
        self.radioChiCuadrado.setChecked(False)
        self.radioChiCuadrado.setObjectName("radioChiCuadrado")
        self.label = QtWidgets.QLabel(self.widget_3)
        self.label.setGeometry(QtCore.QRect(20, 70, 138, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tablaResultados = QtWidgets.QTableView(self.widget_3)
        self.tablaResultados.setGeometry(QtCore.QRect(270, 80, 591, 541))
        self.tablaResultados.setStyleSheet("QTableView {\n"
"    border: 2px solid #F79B72;  /* Borde celeste suave */\n"
"    border-radius: 5px;         /* Esquinas redondeadas */\n"
"    padding: 4px;               /* Espaciado interno */\n"
"}")
        self.tablaResultados.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tablaResultados.setObjectName("tablaResultados")
        self.widgetClasesOp = QtWidgets.QWidget(self.widget_3)
        self.widgetClasesOp.setGeometry(QtCore.QRect(10, 430, 241, 101))
        self.widgetClasesOp.setStyleSheet("#widgetClasesOp {\n"
"    border: 2px solid #F79B72;  /* Borde celeste suave */\n"
"    border-radius: 5px;         /* Esquinas redondeadas */\n"
"    padding: 4px;               /* Espaciado interno */\n"
"}")
        self.widgetClasesOp.setObjectName("widgetClasesOp")
        self.label_11 = QtWidgets.QLabel(self.widgetClasesOp)
        self.label_11.setGeometry(QtCore.QRect(10, 60, 108, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_10 = QtWidgets.QLabel(self.widgetClasesOp)
        self.label_10.setGeometry(QtCore.QRect(10, 20, 109, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.inputNumClases = QtWidgets.QLineEdit(self.widgetClasesOp)
        self.inputNumClases.setEnabled(True)
        self.inputNumClases.setGeometry(QtCore.QRect(130, 20, 101, 31))
        self.inputNumClases.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #2A4759;\n"
"    border-radius: 5px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    border: 2px solid #DDDDDD;\n"
"}")
        self.inputNumClases.setObjectName("inputNumClases")
        self.inputAmpClases = QtWidgets.QLineEdit(self.widgetClasesOp)
        self.inputAmpClases.setEnabled(True)
        self.inputAmpClases.setGeometry(QtCore.QRect(130, 60, 101, 31))
        self.inputAmpClases.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #2A4759;\n"
"    border-radius: 5px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    border: 2px solid #DDDDDD;\n"
"}")
        self.inputAmpClases.setObjectName("inputAmpClases")
        self.label_9 = QtWidgets.QLabel(self.widget_3)
        self.label_9.setGeometry(QtCore.QRect(20, 420, 110, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.widget_2 = QtWidgets.QWidget(self.widget_3)
        self.widget_2.setGeometry(QtCore.QRect(10, 550, 241, 151))
        self.widget_2.setStyleSheet("#widget_2 {\n"
"    border: 2px solid #F79B72;  /* Borde celeste suave */\n"
"    border-radius: 5px;         /* Esquinas redondeadas */\n"
"    padding: 4px;               /* Espaciado interno */\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.listaNumGuardados = QtWidgets.QListView(self.widget_2)
        self.listaNumGuardados.setGeometry(QtCore.QRect(10, 30, 221, 111))
        self.listaNumGuardados.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listaNumGuardados.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.listaNumGuardados.setModelColumn(0)
        self.listaNumGuardados.setObjectName("listaNumGuardados")
        self.label_12 = QtWidgets.QLabel(self.widget_3)
        self.label_12.setGeometry(QtCore.QRect(20, 540, 147, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.widgetParametros = QtWidgets.QWidget(self.widget_3)
        self.widgetParametros.setGeometry(QtCore.QRect(10, 180, 241, 221))
        self.widgetParametros.setStyleSheet("#widgetParametros {\n"
"    border: 2px solid #F79B72;  /* Borde celeste suave */\n"
"    border-radius: 5px;         /* Esquinas redondeadas */\n"
"    padding: 4px;               /* Espaciado interno */\n"
"}")
        self.widgetParametros.setObjectName("widgetParametros")
        self.inputLimInf = QtWidgets.QLineEdit(self.widgetParametros)
        self.inputLimInf.setEnabled(True)
        self.inputLimInf.setGeometry(QtCore.QRect(110, 20, 121, 31))
        self.inputLimInf.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #2A4759;\n"
"    border-radius: 5px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    border: 2px solid #DDDDDD;\n"
"}")
        self.inputLimInf.setPlaceholderText("")
        self.inputLimInf.setObjectName("inputLimInf")
        self.label_8 = QtWidgets.QLabel(self.widgetParametros)
        self.label_8.setGeometry(QtCore.QRect(10, 20, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.line = QtWidgets.QFrame(self.widgetParametros)
        self.line.setGeometry(QtCore.QRect(10, 100, 221, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(self.widgetParametros)
        self.label_2.setGeometry(QtCore.QRect(10, 130, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.inputMediaN = QtWidgets.QLineEdit(self.widgetParametros)
        self.inputMediaN.setEnabled(False)
        self.inputMediaN.setGeometry(QtCore.QRect(110, 130, 121, 31))
        self.inputMediaN.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #2A4759;\n"
"    border-radius: 5px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    border: 2px solid #DDDDDD;\n"
"}")
        self.inputMediaN.setPlaceholderText("")
        self.inputMediaN.setObjectName("inputMediaN")
        self.inputStDevN = QtWidgets.QLineEdit(self.widgetParametros)
        self.inputStDevN.setEnabled(False)
        self.inputStDevN.setGeometry(QtCore.QRect(110, 170, 121, 31))
        self.inputStDevN.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #2A4759;\n"
"    border-radius: 5px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    border: 2px solid #DDDDDD;\n"
"}")
        self.inputStDevN.setPlaceholderText("")
        self.inputStDevN.setObjectName("inputStDevN")
        self.label_3 = QtWidgets.QLabel(self.widgetParametros)
        self.label_3.setGeometry(QtCore.QRect(8, 170, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget_3)
        self.label_4.setGeometry(QtCore.QRect(20, 170, 76, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.botonGenerarMarcas = QtWidgets.QPushButton(self.widget_3)
        self.botonGenerarMarcas.setEnabled(True)
        self.botonGenerarMarcas.setGeometry(QtCore.QRect(270, 630, 591, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.botonGenerarMarcas.setFont(font)
        self.botonGenerarMarcas.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.botonGenerarMarcas.setStyleSheet("QPushButton {\n"
"    background-color: #F79B72;\n"
"    color: #FFFFFF;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #44687F;\n"
"    color: #F79B72;\n"
"}\n"
"QPushButton:disabled{\n"
"    background-color: #FFFFFF;\n"
"    border: 2px solid #F79B72;\n"
"    color: #F79B72;\n"
"}")
        self.botonGenerarMarcas.setObjectName("botonGenerarMarcas")
        self.botonGenerarMarcas_2 = QtWidgets.QPushButton(self.widget_3)
        self.botonGenerarMarcas_2.setEnabled(False)
        self.botonGenerarMarcas_2.setGeometry(QtCore.QRect(270, 670, 591, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.botonGenerarMarcas_2.setFont(font)
        self.botonGenerarMarcas_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.botonGenerarMarcas_2.setStyleSheet("QPushButton {\n"
"    background-color: #F79B72;\n"
"    color: #FFFFFF;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #44687F;\n"
"    color: #F79B72;\n"
"}\n"
"QPushButton:disabled{\n"
"    background-color: #FFFFFF;\n"
"    border: 2px solid #F79B72;\n"
"    color: #F79B72;\n"
"}")
        self.botonGenerarMarcas_2.setObjectName("botonGenerarMarcas_2")
        self.inputLimSup = QtWidgets.QLineEdit(self.widget_3)
        self.inputLimSup.setEnabled(True)
        self.inputLimSup.setGeometry(QtCore.QRect(120, 240, 121, 31))
        self.inputLimSup.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #2A4759;\n"
"    border-radius: 5px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    border: 2px solid #DDDDDD;\n"
"}")
        self.inputLimSup.setPlaceholderText("")
        self.inputLimSup.setObjectName("inputLimSup")
        self.label_7 = QtWidgets.QLabel(self.widget_3)
        self.label_7.setGeometry(QtCore.QRect(20, 240, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.widget_4.raise_()
        self.widgetModelo.raise_()
        self.tablaResultados.raise_()
        self.widgetClasesOp.raise_()
        self.label_9.raise_()
        self.widget_2.raise_()
        self.label_12.raise_()
        self.label.raise_()
        self.widgetParametros.raise_()
        self.label_4.raise_()
        self.botonGenerarMarcas.raise_()
        self.botonGenerarMarcas_2.raise_()
        self.inputLimSup.raise_()
        self.label_7.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.botonCerrar.clicked.connect(MainWindow.close) # type: ignore
        self.radioChiCuadrado.clicked['bool'].connect(self.inputMediaN.setEnabled) # type: ignore
        self.radioChiCuadrado.clicked['bool'].connect(self.inputStDevN.setEnabled) # type: ignore
        self.radioRachas.clicked['bool'].connect(self.inputMediaN.setDisabled) # type: ignore
        self.radioRachas.clicked['bool'].connect(self.inputStDevN.setDisabled) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.botonGenerador.setText(_translate("MainWindow", "Generador de Números"))
        self.botonTests.setText(_translate("MainWindow", "Tests"))
        self.botonDistrib.setText(_translate("MainWindow", "Distribuciones"))
        self.botonCerrar.setText(_translate("MainWindow", "Cerrar"))
        self.label_5.setText(_translate("MainWindow", "Generador de Marcas de Clase"))
        self.radioRachas.setText(_translate("MainWindow", "Bernoulli"))
        self.radioChiCuadrado.setText(_translate("MainWindow", "Normal"))
        self.label.setText(_translate("MainWindow", "Modelo de distribución"))
        self.label_11.setText(_translate("MainWindow", "Amplitud de Clase:"))
        self.label_10.setText(_translate("MainWindow", "Numero de Clases:"))
        self.inputNumClases.setPlaceholderText(_translate("MainWindow", "Auto"))
        self.inputAmpClases.setPlaceholderText(_translate("MainWindow", "Auto"))
        self.label_9.setText(_translate("MainWindow", "Clases (Opcional)"))
        self.label_12.setText(_translate("MainWindow", "Selección de la muestra"))
        self.label_8.setText(_translate("MainWindow", "Lim. Inferior: "))
        self.label_2.setText(_translate("MainWindow", "Media (μ):"))
        self.label_3.setText(_translate("MainWindow", "Desvío Est. (σ):"))
        self.label_4.setText(_translate("MainWindow", "Parámetros"))
        self.botonGenerarMarcas.setText(_translate("MainWindow", "Generar Marcas"))
        self.botonGenerarMarcas_2.setText(_translate("MainWindow", "Exportar Datos"))
        self.label_7.setText(_translate("MainWindow", "Lim. Superior: "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
