# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Vista_Generador.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1080, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1080, 720))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: #CCCCCC")
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, -1, 201, 721))
        self.widget.setStyleSheet("background-color:#2A4759")
        self.widget.setObjectName("widget")
        self.botonGenerador = QtWidgets.QPushButton(self.widget)
        self.botonGenerador.setEnabled(False)
        self.botonGenerador.setGeometry(QtCore.QRect(-10, 10, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.botonGenerador.setFont(font)
        self.botonGenerador.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.botonGenerador.setStyleSheet("QPushButton {\n"
"    background-color: #273F4F;  /* color normal */\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #44687F;  /* color al presionar */\n"
"}\n"
"QPushButton:disabled{\n"
"    background-color: #F79B72;\n"
"    color: #FFFFFF;\n"
"}")
        self.botonGenerador.setObjectName("botonGenerador")
        self.botonTests = QtWidgets.QPushButton(self.widget)
        self.botonTests.setEnabled(True)
        self.botonTests.setGeometry(QtCore.QRect(-10, 60, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.botonTests.setFont(font)
        self.botonTests.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.botonTests.setStyleSheet("QPushButton {\n"
"    background-color: #273F4F;  /* color normal */\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #44687F;  /* color al presionar */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #44687F;  /* color al presionar */\n"
"    color: #F79B72;\n"
"}\n"
"QPushButton:disabled{\n"
"    background-color: #F79B72;\n"
"    color: #FFFFFF;\n"
"}")
        self.botonTests.setObjectName("botonTests")
        self.botonDistrib = QtWidgets.QPushButton(self.widget)
        self.botonDistrib.setEnabled(True)
        self.botonDistrib.setGeometry(QtCore.QRect(-10, 110, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.botonDistrib.setFont(font)
        self.botonDistrib.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.botonDistrib.setStyleSheet("QPushButton {\n"
"    background-color: #273F4F;  /* color normal */\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #44687F;  /* color al presionar */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #44687F;  /* color al presionar */\n"
"    color: #F79B72;\n"
"}\n"
"QPushButton:disabled{\n"
"    background-color: #F79B72;\n"
"    color: #FFFFFF;\n"
"}")
        self.botonDistrib.setObjectName("botonDistrib")
        self.botonCerrar = QtWidgets.QPushButton(self.widget)
        self.botonCerrar.setEnabled(True)
        self.botonCerrar.setGeometry(QtCore.QRect(0, 680, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.botonCerrar.setFont(font)
        self.botonCerrar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.botonCerrar.setStyleSheet("QPushButton {\n"
"    background-color: #1E313D;\n"
"    color: white;\n"
"    border-radius: 2px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #EB5B00;\n"
"}")
        self.botonCerrar.setObjectName("botonCerrar")
        self.botonHidro = QtWidgets.QPushButton(self.widget)
        self.botonHidro.setEnabled(True)
        self.botonHidro.setGeometry(QtCore.QRect(-10, 160, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.botonHidro.setFont(font)
        self.botonHidro.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.botonHidro.setStyleSheet("QPushButton {\n"
"    background-color: #273F4F;  /* color normal */\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid #6ac3b3;\n"
"    border-radius: 5px;\n"
"    padding: 4px;\n"
"    background-color: #222222;\n"
"    color: white;\n"
"}\n"
"QPushButton:pressed {\n"
"    color: #6ac3b3;\n"
"}\n"
"QPushButton:disabled{\n"
"    background-color: #F79B72;\n"
"    color: #FFFFFF;\n"
"}")
        self.botonHidro.setObjectName("botonHidro")
        self.widgetResultados = QtWidgets.QWidget(self.centralwidget)
        self.widgetResultados.setGeometry(QtCore.QRect(630, 0, 450, 721))
        self.widgetResultados.setStyleSheet("background-color: #FFFFFF")
        self.widgetResultados.setObjectName("widgetResultados")
        self.plainResultados = QtWidgets.QPlainTextEdit(self.widgetResultados)
        self.plainResultados.setGeometry(QtCore.QRect(20, 80, 411, 491))
        self.plainResultados.setStyleSheet("QPlainTextEdit {\n"
"    border: 2px solid #F79B72;  /* Borde celeste suave */\n"
"    border-radius: 5px;         /* Esquinas redondeadas */\n"
"    padding: 4px;               /* Espaciado interno */\n"
"    background-color: #DDDDDD; /* Fondo claro */\n"
"}")
        self.plainResultados.setReadOnly(True)
        self.plainResultados.setPlainText("")
        self.plainResultados.setBackgroundVisible(False)
        self.plainResultados.setObjectName("plainResultados")
        self.widgetResultadosT = QtWidgets.QWidget(self.widgetResultados)
        self.widgetResultadosT.setGeometry(QtCore.QRect(0, 0, 451, 61))
        self.widgetResultadosT.setStyleSheet("background-color:#2A4759")
        self.widgetResultadosT.setObjectName("widgetResultadosT")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.widgetResultadosT)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 451, 61))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: #FFFFFF;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.widget_2 = QtWidgets.QWidget(self.widgetResultados)
        self.widget_2.setGeometry(QtCore.QRect(0, 609, 451, 111))
        self.widget_2.setStyleSheet("background-color: #F79B72")
        self.widget_2.setObjectName("widget_2")
        self.botonGuardarTxt = QtWidgets.QPushButton(self.widget_2)
        self.botonGuardarTxt.setEnabled(False)
        self.botonGuardarTxt.setGeometry(QtCore.QRect(90, 60, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.botonGuardarTxt.setFont(font)
        self.botonGuardarTxt.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.botonGuardarTxt.setStyleSheet("QPushButton {\n"
"    background-color: #FFFFFF;  /* color normal */\n"
"    color: #F79B72;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #44687F;  /* color al presionar */\n"
"}\n"
"QPushButton:disabled{\n"
"    background-color: #DDDDDD;\n"
"    color: #888888;\n"
"}")
        self.botonGuardarTxt.setObjectName("botonGuardarTxt")
        self.inputNombre = QtWidgets.QLineEdit(self.widget_2)
        self.inputNombre.setEnabled(False)
        self.inputNombre.setGeometry(QtCore.QRect(90, 20, 261, 31))
        self.inputNombre.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #FFFFFF;  /* Borde celeste suave */\n"
"    border-radius: 5px;         /* Esquinas redondeadas */\n"
"    padding: 4px;               /* Espaciado interno */\n"
"    background-color: #DDDDDD; /* Fondo claro */\n"
"}")
        self.inputNombre.setObjectName("inputNombre")
        self.botonSecreto = QtWidgets.QPushButton(self.widgetResultados)
        self.botonSecreto.setGeometry(QtCore.QRect(410, 580, 31, 23))
        self.botonSecreto.setStyleSheet("QPushButton {    \n"
"    background-color: #FFFFFF;\n"
"    border-radius: 5px;\n"
"    color: #FFFFFF\n"
"}\n"
"QPushButton:hover{\n"
"    border: 2px solid #F79B72;\n"
"    color: #F79B72;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #44687F;\n"
"    color: #F79B72;\n"
"}")
        self.botonSecreto.setObjectName("botonSecreto")
        self.widgetParametros = QtWidgets.QWidget(self.centralwidget)
        self.widgetParametros.setGeometry(QtCore.QRect(210, 0, 411, 721))
        self.widgetParametros.setStyleSheet("background-color: #FFFFFF")
        self.widgetParametros.setObjectName("widgetParametros")
        self.widgetParametrosT = QtWidgets.QWidget(self.widgetParametros)
        self.widgetParametrosT.setGeometry(QtCore.QRect(0, 0, 411, 61))
        self.widgetParametrosT.setStyleSheet("background-color:#2A4759")
        self.widgetParametrosT.setObjectName("widgetParametrosT")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.widgetParametrosT)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 411, 61))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: #FFFFFF")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.widgetGenerador = QtWidgets.QWidget(self.widgetParametros)
        self.widgetGenerador.setGeometry(QtCore.QRect(0, 609, 411, 111))
        self.widgetGenerador.setStyleSheet("background-color: #F79B72")
        self.widgetGenerador.setObjectName("widgetGenerador")
        self.inputCantidad = QtWidgets.QLineEdit(self.widgetGenerador)
        self.inputCantidad.setGeometry(QtCore.QRect(80, 20, 261, 31))
        self.inputCantidad.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #FFFFFF;  /* Borde celeste suave */\n"
"    border-radius: 5px;         /* Esquinas redondeadas */\n"
"    padding: 4px;               /* Espaciado interno */\n"
"    background-color: #DDDDDD; /* Fondo claro */\n"
"}")
        self.inputCantidad.setAlignment(QtCore.Qt.AlignCenter)
        self.inputCantidad.setObjectName("inputCantidad")
        self.botonGenerar = QtWidgets.QPushButton(self.widgetGenerador)
        self.botonGenerar.setEnabled(True)
        self.botonGenerar.setGeometry(QtCore.QRect(80, 60, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.botonGenerar.setFont(font)
        self.botonGenerar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.botonGenerar.setStyleSheet("QPushButton {\n"
"    background-color: #FFFFFF;  /* color normal */\n"
"    color: #F79B72;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #44687F;  /* color al presionar */\n"
"}\n"
"QPushButton:disabled{\n"
"    background-color: #DDDDDD;\n"
"    color: #888888;\n"
"}")
        self.botonGenerar.setObjectName("botonGenerar")
        self.widgetMetodos = QtWidgets.QWidget(self.widgetParametros)
        self.widgetMetodos.setGeometry(QtCore.QRect(10, 80, 391, 71))
        self.widgetMetodos.setStyleSheet("#widgetMetodos {\n"
"    border: 2px solid #F79B72;  /* Borde celeste suave */\n"
"    border-radius: 5px;         /* Esquinas redondeadas */\n"
"    padding: 4px;               /* Espaciado interno */\n"
"}")
        self.widgetMetodos.setObjectName("widgetMetodos")
        self.radioCongruencias = QtWidgets.QRadioButton(self.widgetMetodos)
        self.radioCongruencias.setGeometry(QtCore.QRect(210, 30, 156, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioCongruencias.setFont(font)
        self.radioCongruencias.setObjectName("radioCongruencias")
        self.radioVonNeumann = QtWidgets.QRadioButton(self.widgetMetodos)
        self.radioVonNeumann.setGeometry(QtCore.QRect(20, 30, 111, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioVonNeumann.setFont(font)
        self.radioVonNeumann.setChecked(True)
        self.radioVonNeumann.setObjectName("radioVonNeumann")
        self.label_7 = QtWidgets.QLabel(self.widgetParametros)
        self.label_7.setGeometry(QtCore.QRect(20, 70, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("QLabel {\n"
"    background-color: #FFFFFF\n"
"}")
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.widgetParametros)
        self.label_8.setGeometry(QtCore.QRect(20, 160, 42, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("QLabel {\n"
"    background-color: #FFFFFF\n"
"}")
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.widgetDatos = QtWidgets.QWidget(self.widgetParametros)
        self.widgetDatos.setGeometry(QtCore.QRect(10, 170, 391, 301))
        self.widgetDatos.setStyleSheet("#widgetDatos {\n"
"    border: 2px solid #F79B72;  /* Borde celeste suave */\n"
"    border-radius: 5px;         /* Esquinas redondeadas */\n"
"    padding: 4px;               /* Espaciado interno */\n"
"}")
        self.widgetDatos.setObjectName("widgetDatos")
        self.label_6 = QtWidgets.QLabel(self.widgetDatos)
        self.label_6.setGeometry(QtCore.QRect(20, 30, 47, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.inputSemilla = QtWidgets.QLineEdit(self.widgetDatos)
        self.inputSemilla.setEnabled(True)
        self.inputSemilla.setGeometry(QtCore.QRect(70, 30, 301, 31))
        self.inputSemilla.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #2A4759;\n"
"    border-radius: 5px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    border: 2px solid #DDDDDD;\n"
"}")
        self.inputSemilla.setObjectName("inputSemilla")
        self.label_9 = QtWidgets.QLabel(self.widgetDatos)
        self.label_9.setEnabled(False)
        self.label_9.setGeometry(QtCore.QRect(20, 150, 42, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.inputA = QtWidgets.QLineEdit(self.widgetDatos)
        self.inputA.setEnabled(False)
        self.inputA.setGeometry(QtCore.QRect(70, 150, 301, 31))
        self.inputA.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #2A4759;\n"
"    border-radius: 5px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    border: 2px solid #DDDDDD;\n"
"}")
        self.inputA.setObjectName("inputA")
        self.inputC = QtWidgets.QLineEdit(self.widgetDatos)
        self.inputC.setEnabled(False)
        self.inputC.setGeometry(QtCore.QRect(70, 200, 301, 31))
        self.inputC.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #2A4759;\n"
"    border-radius: 5px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    border: 2px solid #DDDDDD;\n"
"}")
        self.inputC.setText("")
        self.inputC.setObjectName("inputC")
        self.label_10 = QtWidgets.QLabel(self.widgetDatos)
        self.label_10.setEnabled(False)
        self.label_10.setGeometry(QtCore.QRect(20, 200, 42, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.widgetDatos)
        self.label_11.setEnabled(False)
        self.label_11.setGeometry(QtCore.QRect(20, 250, 42, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.inputM = QtWidgets.QLineEdit(self.widgetDatos)
        self.inputM.setEnabled(False)
        self.inputM.setGeometry(QtCore.QRect(70, 250, 301, 31))
        self.inputM.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #2A4759;\n"
"    border-radius: 5px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    border: 2px solid #DDDDDD;\n"
"}")
        self.inputM.setText("")
        self.inputM.setObjectName("inputM")
        self.labelVonNeumann = QtWidgets.QLabel(self.widgetDatos)
        self.labelVonNeumann.setGeometry(QtCore.QRect(80, 61, 161, 20))
        self.labelVonNeumann.setStyleSheet("color: #888888")
        self.labelVonNeumann.setObjectName("labelVonNeumann")
        self.line = QtWidgets.QFrame(self.widgetDatos)
        self.line.setGeometry(QtCore.QRect(10, 90, 371, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(self.widgetDatos)
        self.label.setGeometry(QtCore.QRect(20, 110, 199, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.botonLimpiar = QtWidgets.QPushButton(self.widgetParametros)
        self.botonLimpiar.setEnabled(True)
        self.botonLimpiar.setGeometry(QtCore.QRect(10, 480, 391, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.botonLimpiar.setFont(font)
        self.botonLimpiar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.botonLimpiar.setStyleSheet("QPushButton {\n"
"    background-color: #FFFFFF;\n"
"    border: 2px solid #F79B72;\n"
"    color: #F79B72;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #44687F;\n"
"    color: #F79B72;\n"
"}\n"
"QPushButton:disabled{\n"
"    background-color: #FFFFFF;\n"
"    border: 2px solid #F79B72;\n"
"    color: #F79B72;\n"
"}")
        self.botonLimpiar.setObjectName("botonLimpiar")
        self.widgetParametrosT.raise_()
        self.widgetGenerador.raise_()
        self.widgetMetodos.raise_()
        self.label_7.raise_()
        self.widgetDatos.raise_()
        self.label_8.raise_()
        self.botonLimpiar.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.radioVonNeumann.toggled['bool'].connect(self.labelVonNeumann.setVisible) # type: ignore
        self.radioCongruencias.toggled['bool'].connect(self.label_9.setEnabled) # type: ignore
        self.radioCongruencias.toggled['bool'].connect(self.inputA.setEnabled) # type: ignore
        self.radioCongruencias.toggled['bool'].connect(self.label_10.setEnabled) # type: ignore
        self.radioCongruencias.toggled['bool'].connect(self.inputC.setEnabled) # type: ignore
        self.radioCongruencias.toggled['bool'].connect(self.label_11.setEnabled) # type: ignore
        self.radioCongruencias.toggled['bool'].connect(self.inputM.setEnabled) # type: ignore
        self.radioCongruencias.toggled['bool'].connect(self.label.setEnabled) # type: ignore
        self.botonLimpiar.clicked.connect(self.inputM.clear) # type: ignore
        self.botonLimpiar.clicked.connect(self.inputC.clear) # type: ignore
        self.botonLimpiar.clicked.connect(self.inputA.clear) # type: ignore
        self.botonLimpiar.clicked.connect(self.inputSemilla.clear) # type: ignore
        self.botonCerrar.clicked.connect(MainWindow.close) # type: ignore
        self.botonLimpiar.clicked.connect(self.plainResultados.clear) # type: ignore
        self.botonLimpiar.clicked.connect(self.inputCantidad.clear) # type: ignore
        self.botonLimpiar.clicked['bool'].connect(self.inputNombre.setEnabled) # type: ignore
        self.botonLimpiar.clicked['bool'].connect(self.botonGuardarTxt.setEnabled) # type: ignore
        self.botonLimpiar.clicked.connect(self.inputNombre.clear) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.botonGenerador.setText(_translate("MainWindow", "Generador de Números"))
        self.botonTests.setText(_translate("MainWindow", "Tests"))
        self.botonDistrib.setText(_translate("MainWindow", "Distribuciones"))
        self.botonCerrar.setText(_translate("MainWindow", "Cerrar"))
        self.botonHidro.setText(_translate("MainWindow", "HidroStat (FInal)"))
        self.plainResultados.setPlaceholderText(_translate("MainWindow", "Números Generados..."))
        self.label_5.setText(_translate("MainWindow", "Números Generados"))
        self.botonGuardarTxt.setText(_translate("MainWindow", "Guardar TXT"))
        self.inputNombre.setPlaceholderText(_translate("MainWindow", "Nombre del archivo (opcional)"))
        self.botonSecreto.setText(_translate("MainWindow", "?"))
        self.label_4.setText(_translate("MainWindow", "Parámetros"))
        self.inputCantidad.setPlaceholderText(_translate("MainWindow", "Cantidad de Números a Generar"))
        self.botonGenerar.setText(_translate("MainWindow", "Generar Números"))
        self.radioCongruencias.setText(_translate("MainWindow", "Congruencias Mixtas"))
        self.radioVonNeumann.setText(_translate("MainWindow", "VonNeumann"))
        self.label_7.setText(_translate("MainWindow", "Método de Generación"))
        self.label_8.setText(_translate("MainWindow", "Datos"))
        self.label_6.setText(_translate("MainWindow", "Semilla:"))
        self.inputSemilla.setPlaceholderText(_translate("MainWindow", "Entero positivo"))
        self.label_9.setText(_translate("MainWindow", "A:"))
        self.inputA.setPlaceholderText(_translate("MainWindow", "Entero positivo e impar"))
        self.inputC.setPlaceholderText(_translate("MainWindow", "Entero impar, positivo, relativamente primo a M"))
        self.label_10.setText(_translate("MainWindow", "C:"))
        self.label_11.setText(_translate("MainWindow", "M:"))
        self.inputM.setPlaceholderText(_translate("MainWindow", "Entero positivo, mayor que A y mayor que la Semilla"))
        self.labelVonNeumann.setText(_translate("MainWindow", "* La semilla debe tener 4 dígitos"))
        self.label.setText(_translate("MainWindow", "Valores para Congruencias Mixtas:"))
        self.botonLimpiar.setText(_translate("MainWindow", "Limpiar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
