# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Vista_Tester.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1080, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1080, 720))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: #CCCCCC")
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, -1, 201, 721))
        self.widget.setStyleSheet("background-color:#2A4759")
        self.widget.setObjectName("widget")
        self.botonGenerador = QtWidgets.QPushButton(self.widget)
        self.botonGenerador.setEnabled(True)
        self.botonGenerador.setGeometry(QtCore.QRect(-10, 10, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.botonGenerador.setFont(font)
        self.botonGenerador.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.botonGenerador.setStyleSheet("QPushButton {\n"
"    background-color: #273F4F;  /* color normal */\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #44687F;  /* color al presionar */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #44687F;  /* color al presionar */\n"
"    color: #F79B72;\n"
"}\n"
"QPushButton:disabled{\n"
"    background-color: #F79B72;\n"
"    color: #FFFFFF;\n"
"}")
        self.botonGenerador.setObjectName("botonGenerador")
        self.botonTests = QtWidgets.QPushButton(self.widget)
        self.botonTests.setEnabled(False)
        self.botonTests.setGeometry(QtCore.QRect(-10, 60, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.botonTests.setFont(font)
        self.botonTests.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.botonTests.setStyleSheet("QPushButton {\n"
"    background-color: #273F4F;  /* color normal */\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #44687F;  /* color al presionar */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #44687F;  /* color al presionar */\n"
"    color: #F79B72;\n"
"}\n"
"QPushButton:disabled{\n"
"    background-color: #F79B72;\n"
"    color: #FFFFFF;\n"
"}")
        self.botonTests.setObjectName("botonTests")
        self.botonDistrib = QtWidgets.QPushButton(self.widget)
        self.botonDistrib.setGeometry(QtCore.QRect(-10, 110, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.botonDistrib.setFont(font)
        self.botonDistrib.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.botonDistrib.setStyleSheet("QPushButton {\n"
"    background-color: #273F4F;  /* color normal */\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #44687F;  /* color al presionar */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #44687F;  /* color al presionar */\n"
"    color: #F79B72;\n"
"}\n"
"QPushButton:disabled{\n"
"    background-color: #F79B72;\n"
"    color: #FFFFFF;\n"
"}")
        self.botonDistrib.setObjectName("botonDistrib")
        self.botonCerrar = QtWidgets.QPushButton(self.widget)
        self.botonCerrar.setGeometry(QtCore.QRect(0, 680, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.botonCerrar.setFont(font)
        self.botonCerrar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.botonCerrar.setStyleSheet("QPushButton {\n"
"    background-color: #1E313D;\n"
"    color: white;\n"
"    border-radius: 2px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #EB5B00;\n"
"}")
        self.botonCerrar.setObjectName("botonCerrar")
        self.widgetBD = QtWidgets.QWidget(self.widget)
        self.widgetBD.setGeometry(QtCore.QRect(10, 450, 181, 211))
        self.widgetBD.setStyleSheet("#widgetBD {\n"
"    border: 2px solid #FFFFFF;  /* Borde celeste suave */\n"
"    border-radius: 5px;         /* Esquinas redondeadas */\n"
"    padding: 4px;               /* Espaciado interno */\n"
"}")
        self.widgetBD.setObjectName("widgetBD")
        self.checkRachas = QtWidgets.QCheckBox(self.widgetBD)
        self.checkRachas.setEnabled(False)
        self.checkRachas.setGeometry(QtCore.QRect(10, 10, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkRachas.setFont(font)
        self.checkRachas.setStyleSheet("QCheckBox {\n"
"    color: #FFFFFF\n"
"}\n"
"QCheckBox:checked {\n"
"    color: #7ef29d\n"
"}")
        self.checkRachas.setCheckable(True)
        self.checkRachas.setChecked(False)
        self.checkRachas.setObjectName("checkRachas")
        self.checkChiCuadrado = QtWidgets.QCheckBox(self.widgetBD)
        self.checkChiCuadrado.setEnabled(False)
        self.checkChiCuadrado.setGeometry(QtCore.QRect(10, 40, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkChiCuadrado.setFont(font)
        self.checkChiCuadrado.setStyleSheet("QCheckBox {\n"
"    color: #FFFFFF\n"
"}\n"
"QCheckBox:checked {\n"
"    color: #7ef29d\n"
"}")
        self.checkChiCuadrado.setCheckable(True)
        self.checkChiCuadrado.setChecked(False)
        self.checkChiCuadrado.setObjectName("checkChiCuadrado")
        self.botonGuardarBD = QtWidgets.QPushButton(self.widgetBD)
        self.botonGuardarBD.setEnabled(False)
        self.botonGuardarBD.setGeometry(QtCore.QRect(10, 110, 161, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.botonGuardarBD.setFont(font)
        self.botonGuardarBD.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.botonGuardarBD.setStyleSheet("QPushButton {\n"
"    background-color: #3bba00;  /* color normal */\n"
"    color: #FFFFFF;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #267800;  /* color al presionar */\n"
"}\n"
"QPushButton:disabled{\n"
"    background-color: #44687F;\n"
"    color: #BBBBBB\n"
"}")
        self.botonGuardarBD.setObjectName("botonGuardarBD")
        self.botonDescartar = QtWidgets.QPushButton(self.widgetBD)
        self.botonDescartar.setEnabled(False)
        self.botonDescartar.setGeometry(QtCore.QRect(10, 160, 161, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.botonDescartar.setFont(font)
        self.botonDescartar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.botonDescartar.setStyleSheet("QPushButton {\n"
"    background-color: #EB5B00;  /* color normal */\n"
"    color: #FFFFFF;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #913800;  /* color al presionar */\n"
"}\n"
"QPushButton:disabled{\n"
"    background-color: #44687F;\n"
"    color: #BBBBBB\n"
"}")
        self.botonDescartar.setObjectName("botonDescartar")
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(209, 0, 871, 721))
        self.widget_3.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.widget_3.setToolTip("")
        self.widget_3.setToolTipDuration(-1)
        self.widget_3.setStyleSheet("background-color: #FFFFFF")
        self.widget_3.setObjectName("widget_3")
        self.widget_4 = QtWidgets.QWidget(self.widget_3)
        self.widget_4.setGeometry(QtCore.QRect(0, 0, 871, 61))
        self.widget_4.setStyleSheet("background-color:#2A4759")
        self.widget_4.setObjectName("widget_4")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.widget_4)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 871, 61))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: #FFFFFF;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.widgetMetodo = QtWidgets.QWidget(self.widget_3)
        self.widgetMetodo.setGeometry(QtCore.QRect(10, 80, 241, 171))
        self.widgetMetodo.setStyleSheet("#widgetMetodo {\n"
"    border: 2px solid #F79B72;  /* Borde celeste suave */\n"
"    border-radius: 5px;         /* Esquinas redondeadas */\n"
"    padding: 4px;               /* Espaciado interno */\n"
"}")
        self.widgetMetodo.setObjectName("widgetMetodo")
        self.radioChiCuadrado = QtWidgets.QRadioButton(self.widgetMetodo)
        self.radioChiCuadrado.setGeometry(QtCore.QRect(30, 20, 109, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioChiCuadrado.setFont(font)
        self.radioChiCuadrado.setChecked(True)
        self.radioChiCuadrado.setObjectName("radioChiCuadrado")
        self.radioRachas = QtWidgets.QRadioButton(self.widgetMetodo)
        self.radioRachas.setGeometry(QtCore.QRect(30, 60, 109, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioRachas.setFont(font)
        self.radioRachas.setObjectName("radioRachas")
        self.line = QtWidgets.QFrame(self.widgetMetodo)
        self.line.setGeometry(QtCore.QRect(10, 90, 221, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(self.widgetMetodo)
        self.label_2.setGeometry(QtCore.QRect(20, 120, 103, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.inputSignificancia = QtWidgets.QDoubleSpinBox(self.widgetMetodo)
        self.inputSignificancia.setGeometry(QtCore.QRect(130, 120, 91, 31))
        self.inputSignificancia.setStyleSheet("QDoubleSpinBox {\n"
"    border: 2px solid #DDDDDD;  /* Borde celeste suave */\n"
"    border-radius: 5px;         /* Esquinas redondeadas */\n"
"    padding: 4px;               /* Espaciado interno */\n"
"}")
        self.inputSignificancia.setFrame(True)
        self.inputSignificancia.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.inputSignificancia.setMinimum(0.01)
        self.inputSignificancia.setMaximum(0.99)
        self.inputSignificancia.setSingleStep(0.01)
        self.inputSignificancia.setProperty("value", 0.05)
        self.inputSignificancia.setObjectName("inputSignificancia")
        self.label = QtWidgets.QLabel(self.widget_3)
        self.label.setGeometry(QtCore.QRect(20, 70, 114, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.plainPrevistaNum = QtWidgets.QPlainTextEdit(self.widget_3)
        self.plainPrevistaNum.setGeometry(QtCore.QRect(270, 80, 591, 171))
        self.plainPrevistaNum.setStyleSheet("QPlainTextEdit {\n"
"    border: 2px solid #F79B72;  /* Borde celeste suave */\n"
"    border-radius: 5px;         /* Esquinas redondeadas */\n"
"    padding: 4px;               /* Espaciado interno */\n"
"    background-color: #DDDDDD; /* Fondo claro */\n"
"}")
        self.plainPrevistaNum.setReadOnly(True)
        self.plainPrevistaNum.setBackgroundVisible(False)
        self.plainPrevistaNum.setObjectName("plainPrevistaNum")
        self.widget_8 = QtWidgets.QWidget(self.widget_3)
        self.widget_8.setGeometry(QtCore.QRect(0, 620, 871, 101))
        self.widget_8.setStyleSheet("background-color: #F79B72")
        self.widget_8.setObjectName("widget_8")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.widget_8)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 871, 101))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(200, 0, 200, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.botonIniciarTest = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.botonIniciarTest.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.botonIniciarTest.setFont(font)
        self.botonIniciarTest.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.botonIniciarTest.setStyleSheet("QPushButton {\n"
"    background-color: #FFFFFF;  /* color normal */\n"
"    color: #F79B72;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #44687F;  /* color al presionar */\n"
"}\n"
"QPushButton:disabled{\n"
"    background-color: #F79B72;\n"
"    color: #FFFFFF;\n"
"}")
        self.botonIniciarTest.setObjectName("botonIniciarTest")
        self.verticalLayout_2.addWidget(self.botonIniciarTest)
        self.lineResultado = QtWidgets.QLineEdit(self.widget_3)
        self.lineResultado.setGeometry(QtCore.QRect(10, 570, 851, 41))
        self.lineResultado.setCursor(QtGui.QCursor(QtCore.Qt.UpArrowCursor))
        self.lineResultado.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineResultado.setAcceptDrops(False)
        self.lineResultado.setToolTip("")
        self.lineResultado.setToolTipDuration(1)
        self.lineResultado.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #F79B72;  /* Borde celeste suave */\n"
"    border-radius: 5px;         /* Esquinas redondeadas */\n"
"    padding: 4px;               /* Espaciado interno */\n"
"    background-color: #DDDDDD; /* Fondo claro */\n"
"    color: #888888\n"
"}")
        self.lineResultado.setAlignment(QtCore.Qt.AlignCenter)
        self.lineResultado.setReadOnly(True)
        self.lineResultado.setObjectName("lineResultado")
        self.widget_2 = QtWidgets.QWidget(self.widget_3)
        self.widget_2.setGeometry(QtCore.QRect(10, 280, 241, 271))
        self.widget_2.setStyleSheet("#widget_2 {\n"
"    border: 2px solid #F79B72;  /* Borde celeste suave */\n"
"    border-radius: 5px;         /* Esquinas redondeadas */\n"
"    padding: 4px;               /* Espaciado interno */\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.listaNumGuardados = QtWidgets.QListView(self.widget_2)
        self.listaNumGuardados.setGeometry(QtCore.QRect(10, 18, 221, 241))
        self.listaNumGuardados.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listaNumGuardados.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.listaNumGuardados.setModelColumn(0)
        self.listaNumGuardados.setObjectName("listaNumGuardados")
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        self.label_3.setGeometry(QtCore.QRect(20, 260, 138, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget_3)
        self.label_4.setGeometry(QtCore.QRect(280, 260, 163, 14))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: #888888")
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.widget_3)
        self.label_6.setGeometry(QtCore.QRect(460, 260, 181, 14))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: #888888")
        self.label_6.setObjectName("label_6")
        self.tablaResultados = QtWidgets.QTableView(self.widget_3)
        self.tablaResultados.setGeometry(QtCore.QRect(270, 281, 591, 271))
        self.tablaResultados.setStyleSheet("QTableView {\n"
"    border: 2px solid #F79B72;  /* Borde celeste suave */\n"
"    border-radius: 5px;         /* Esquinas redondeadas */\n"
"    padding: 4px;               /* Espaciado interno */\n"
"}")
        self.tablaResultados.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tablaResultados.setObjectName("tablaResultados")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.botonCerrar.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.botonGenerador.setText(_translate("MainWindow", "Generador de Números"))
        self.botonTests.setText(_translate("MainWindow", "Tests"))
        self.botonDistrib.setText(_translate("MainWindow", "Distribuciones"))
        self.botonCerrar.setText(_translate("MainWindow", "Cerrar"))
        self.checkRachas.setText(_translate("MainWindow", "Prueba de Rachas"))
        self.checkChiCuadrado.setText(_translate("MainWindow", "Prueba de Chi Cuadrado"))
        self.botonGuardarBD.setText(_translate("MainWindow", "Guardar"))
        self.botonDescartar.setText(_translate("MainWindow", "Descartar"))
        self.label_5.setText(_translate("MainWindow", "Test de Aleatoriedad"))
        self.radioChiCuadrado.setText(_translate("MainWindow", "Chi Cuadrado"))
        self.radioRachas.setText(_translate("MainWindow", "Rachas"))
        self.label_2.setText(_translate("MainWindow", "Signficancia (α):"))
        self.label.setText(_translate("MainWindow", "Método de Prueba"))
        self.plainPrevistaNum.setPlaceholderText(_translate("MainWindow", "No se ha seleccionado ninguna secuencia de números..."))
        self.botonIniciarTest.setText(_translate("MainWindow", "Iniciar Prueba"))
        self.lineResultado.setText(_translate("MainWindow", "Sin resultados aún..."))
        self.lineResultado.setPlaceholderText(_translate("MainWindow", "Sin resultados aún..."))
        self.label_3.setText(_translate("MainWindow", "Secuencias guardadas"))
        self.label_4.setText(_translate("MainWindow", "*H₀: La secuencia es aleatoria"))
        self.label_6.setText(_translate("MainWindow", "*H₁: La secuencia no es aleatoria"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
