# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'secreto.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_secretDialog(object):
    def setupUi(self, secretDialog):
        secretDialog.setObjectName("secretDialog")
        secretDialog.resize(400, 400)
        secretDialog.setMinimumSize(QtCore.QSize(400, 400))
        secretDialog.setMaximumSize(QtCore.QSize(400, 400))
        self.widget = QtWidgets.QWidget(secretDialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 401, 401))
        self.widget.setStyleSheet(f"""
            QWidget {{
                background-image: url("{QtCore.QDir.currentPath()}/data/secreto.jpg");
                background-repeat: no-repeat;
                background-position: center;
            }}
        """)
        self.widget.setObjectName("widget")

        self.retranslateUi(secretDialog)
        QtCore.QMetaObject.connectSlotsByName(secretDialog)

    def retranslateUi(self, secretDialog):
        _translate = QtCore.QCoreApplication.translate
        secretDialog.setWindowTitle(_translate("secretDialog", "Dialog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    secretDialog = QtWidgets.QDialog()
    ui = Ui_secretDialog()
    ui.setupUi(secretDialog)
    secretDialog.show()
    sys.exit(app.exec_())
